/*--------------------------------------------------
	=============== Language Files ===============
	*** Copyright (c) 2012-2020 by DrVrej, All rights reserved. ***
	No parts of this code or any of its contents may be reproduced, copied, modified or adapted,
	without the prior written consent of the author, unless otherwise indicated for stand-alone materials.
--------------------------------------------------*/
if (!file.Exists("autorun/vj_base_autorun.lua","LUA")) then return end
include('autorun/vj_controls.lua')

/*
	How it works:
		* Looks for the current set language and translates all the strings that are given.
		* If a string isn't translated, it will automatically default to English.
		* When a updated while in a map, it will try to refresh some of the menus, but many menus requires a map restart!
	
	How to edit & contribute:
		* Make any edits in any language you would like.
		* If a line doesn't exist in your language, then copy & paste it from the default (English) list.
		* Once you are done translating or editing, you can push the edited file on GitHub.
		* Once the file is pushed, I will review it and merge it with the base, it will then be included with the next update on Workshop.
		* NOTE: Over time more lines will be added in the default (English) list. You are welcome to check back whenever and copy & paste any new lines that added and translate it.
	
	Q: I would like to translate and my language isn't listed below =(
	A: No worries! Just simply contact me (DrVrej) and I will set up the profile for your language!
	
	Q: Someone has already translated my language, how can I contribute now?
	A: You can go over the translated lines and fix any errors. You can also compare it with the English version and make sure all lines are translated!
	
	Thank you to all of your contributions everyone!
*/

VJ.AddClientConVar("vj_language", "english", "Display developer entities") -- The current VJ Base Language

if (CLIENT) then
	local function add(name, str) -- Aveli tirountsnelou hamar e
		language.Add(name, str)
	end
	
	function VJ_REFRESH_LANGUAGE()
		local conv = GetConVar("vj_language"):GetString()
		
		-- DEFAULT (English) LIST | Copy & paste any of the lines below to your preferred language to translate it.
		add("vjbase.menugeneral.default", "Default") -- DO NOT TRANSLATE. (Deprecated)
		
		-- General Base (Used everywhere)
		// add("vjbase.general.print.runningvj", "Notice: This server is running VJ Base.") -- DO NOT TRANSLATE.
		
		-- General Menu (Used everywhere)
		add("vjbase.menu.general.default", "Default")
		add("vjbase.menu.general.admin.only", "Notice: Only admins can use this menu.")
		add("vjbase.menu.general.admin.not", "You are not a admin!")
		add("vjbase.menu.general.reset.everything", "Reset To Default")
		add("vjbase.menu.general.snpc.warnfuture", "WARNING: Only future spawned SNPCs will be affected!")
		add("vjbase.menu.general.snpc.creaturesettings", "Creature Settings:")
		add("vjbase.menu.general.snpc.humansettings", "Human Settings:")
		
		-- Menu Tabs
		add("vjbase.menu.tabs.mainmenu", "Main Menu")
		add("vjbase.menu.tabs.settings.snpc", "SNPC Settings")
		add("vjbase.menu.tabs.settings.weapon", "Weapon Settings")
		add("vjbase.menu.tabs.settings.hud", "HUD Settings")
		add("vjbase.menu.tabs.tools", "Tools")
		add("vjbase.menu.tabs.configures.snpc", "SNPC Configures")
		
		-- Main Menu
		add("vjbase.menu.cleanup", "Clean Up")
		add("vjbase.menu.cleanup.everything", "Clean Up Everything")
		add("vjbase.menu.cleanup.stopsounds", "Stop all Sounds")
		add("vjbase.menu.cleanup.remove.vjnpcs", "Remove all VJ SNPCs")
		add("vjbase.menu.cleanup.remove.npcs", "Remove all (S)NPCs")
		add("vjbase.menu.cleanup.remove.spawners", "Remove all Spawners")
		add("vjbase.menu.cleanup.remove.corpses", "Remove all Corpses")
		add("vjbase.menu.cleanup.remove.vjgibs", "Remove all VJ Gibs")
		add("vjbase.menu.cleanup.remove.groundweapons", "Remove all Ground Weapons")
		add("vjbase.menu.cleanup.remove.props", "Remove all Props")
		add("vjbase.menu.cleanup.remove.decals", "Remove all Decals")
		add("vjbase.menu.cleanup.remove.allweapons", "Remove all of your Weapons")
		add("vjbase.menu.cleanup.remove.allammo", "Remove all of your Ammo")
		
		add("vjbase.menu.helpsupport", "Contact and Support")
		add("vjbase.menu.helpsupport.reportbug", "Report a Bug")
		add("vjbase.menu.helpsupport.suggestion", "Suggest Something")
		add("vjbase.menu.helpsupport.discord", "Join me on Discord!")
		add("vjbase.menu.helpsupport.steam", "Join me on Steam!")
		add("vjbase.menu.helpsupport.youtube", "Subscribe me on YouTube!")
		add("vjbase.menu.helpsupport.twitter", "Follow me on Twitter!")
		add("vjbase.menu.helpsupport.patreon", "Donate me on Patreon!")
		add("vjbase.menu.helpsupport.label1", "Follow one of these links to get updates about my addons!")
		add("vjbase.menu.helpsupport.label2", "Donations help and encourage me to continue making/updating addons! Thank you!")
		add("vjbase.menu.helpsupport.thanks", "Thanks for your support!")
		
		add("vjbase.menu.svsettings", "Admin Server Settings")
		add("vjbase.menu.svsettings.label", "WARNING: SOME SETTINGS NEED CHEATS ENABLED!")
		add("vjbase.menu.svsettings.admin.npcproperties", "Restrict SNPC Properties to Admins Only")
		add("vjbase.menu.svsettings.noclip", "Allow NoClip")
		add("vjbase.menu.svsettings.weapons", "Allow Weapons")
		add("vjbase.menu.svsettings.pvp", "Allow PvP")
		add("vjbase.menu.svsettings.godmode", "God Mode (Everyone)")
		add("vjbase.menu.svsettings.bonemanip.npcs", "Bone Manipulate NPCs")
		add("vjbase.menu.svsettings.bonemanip.players", "Bone Manipulate Players")
		add("vjbase.menu.svsettings.bonemanip.others", "Bone Manipulate Others")
		add("vjbase.menu.svsettings.timescale.general", "General TimeScale")
		add("vjbase.menu.svsettings.timescale.physics", "Physics TimeScale")
		add("vjbase.menu.svsettings.gravity", "General Gravity")
		add("vjbase.menu.svsettings.maxentsprops", "Max Props/Entities:")
		
		add("vjbase.menu.clsettings", "Client Settings")
		add("vjbase.menu.clsettings.label", "Use this menu to customize your client settings, servers can't change these settings!")
		add("vjbase.menu.clsettings.labellang", "Language Selection...")
		add("vjbase.menu.clsettings.notify.lang", "VJ Base Language Set To:")
		
		add("vjbase.menu.info", "Information")
		
		add("vjbase.menu.plugins", "Installed Plugins")
		add("vjbase.menu.plugins.label", "List of installed VJ Base plugins.")
		add("vjbase.menu.plugins.version", "Version:")
		add("vjbase.menu.plugins.totalplugins", "Total Plugins:")
		add("vjbase.menu.plugins.header1", "Name")
		add("vjbase.menu.plugins.header2", "Type")
		add("vjbase.menu.plugins.notfound", "No Plugins Found.")
		add("vjbase.menu.plugins.changelog", "Changelog")
		add("vjbase.menu.plugins.makeaddon", "Want to make an addon? Click Here!")
		
		-- SNPC Menus
		add("vjbase.menu.snpc.options", "Options")
		add("vjbase.menu.snpc.options.difficulty.header", "Select the Difficulty:")
		add("vjbase.menu.snpc.options.difficulty.neanderthal", "Neanderthal | -99% Health and Damage")
		add("vjbase.menu.snpc.options.difficulty.childs_play", "Child's Play | -75% Health and Damage")
		add("vjbase.menu.snpc.options.difficulty.easy", "Easy | -50% Health and Damage")
		add("vjbase.menu.snpc.options.difficulty.normal", "Normal | Original Health and Damage")
		add("vjbase.menu.snpc.options.difficulty.hard", "Hard | +50% Health and Damage")
		add("vjbase.menu.snpc.options.difficulty.insane", "Insane | +100% Health and Damage")
		add("vjbase.menu.snpc.options.difficulty.impossible", "Impossible | +150% Health and Damage")
		add("vjbase.menu.snpc.options.difficulty.nightmare", "Nightmare | +250% Health and Damage")
		add("vjbase.menu.snpc.options.difficulty.hell_on_earth", "Hell On Earth | +350% Health and Damage")
		add("vjbase.menu.snpc.options.difficulty.total_annihilation", "Total Annihilation | +500% Health and Damage")
		add("vjbase.menu.snpc.options.label1", "Relationship Options:")
		add("vjbase.menu.snpc.options.togglefriendlyantlion", "Antlion Friendly")
		add("vjbase.menu.snpc.options.togglefriendlycombine", "Combine Friendly")
		add("vjbase.menu.snpc.options.togglefriendlyplayer", "Player Friendly")
		add("vjbase.menu.snpc.options.togglefriendlyzombie", "Zombie Friendly")
		add("vjbase.menu.snpc.options.togglefriendlyvj", "VJ Base Friendly")
		add("vjbase.menu.snpc.options.label2", "All VJ SNPCs will be allied!")
		add("vjbase.menu.snpc.options.label3", "Corpse & Health Options:")
		add("vjbase.menu.snpc.options.corpselimit", "Corpse Limit, Def:32")
		add("vjbase.menu.snpc.options.label4", "Corpse Limit when 'Keep Corpses' is off")
		add("vjbase.menu.snpc.options.toggleundocorpses", "Undoable Corpses (Undo Key)")
		add("vjbase.menu.snpc.options.togglecorpsefade", "Fade Corpses")
		add("vjbase.menu.snpc.options.corpsefadetime", "Corpse Fade Time")
		add("vjbase.menu.snpc.options.label5", "Total: 600 seconds (10 Minutes)")
		add("vjbase.menu.snpc.options.togglegibcollision", "Collidable Gibs")
		add("vjbase.menu.snpc.options.togglefadegibs", "Fade Gibs")
		add("vjbase.menu.snpc.options.gibfadetime", "Gib Fade Time")
		add("vjbase.menu.snpc.options.label6", "Default: 30 | Total: 600 seconds (10 Minutes)")
		add("vjbase.menu.snpc.options.togglesnpcgodmode", "God Mode (They won't take any damage)")
		add("vjbase.menu.snpc.options.health", "Health:")
		add("vjbase.menu.snpc.options.defaulthealth", "0 = Default Health (9 digits max!)")
		add("vjbase.menu.snpc.options.label7", "AI Options:")
		add("vjbase.menu.snpc.options.toggleknowenemylocation", "Always Know Enemy Location")
		add("vjbase.menu.snpc.options.sightdistance", "Sight Distance:")
		add("vjbase.menu.snpc.options.label8", "Each NPC has its own distance, but this will make them all the same, so use it cautiously! (0 = Original | Average: 10k)")
		add("vjbase.menu.snpc.options.processtime", "Process Time")
		add("vjbase.menu.snpc.options.whatisprocesstime", "What is Process Time?")
		add("vjbase.menu.snpc.options.label9", "Default: 1 | Lower number causes more lag!")
		add("vjbase.menu.snpc.options.label10", "Miscellaneous Options:")
		add("vjbase.menu.snpc.options.togglegmoddecals", "Use Garry's Mod's Current Blood Decals")
		add("vjbase.menu.snpc.options.label11", "Colors that aren't Yellow or Red won't change!")
		add("vjbase.menu.snpc.options.toggleitemdrops", "Item Drops On Death")
		add("vjbase.menu.snpc.options.toggleshowhudonkilled", "Show HUD Display on SNPC killed (Top Right)")
		add("vjbase.menu.snpc.options.toggleaddfrags", "Add points to the player's scoreboard when killed")
		add("vjbase.menu.snpc.options.togglecreatureopendoor", "Creatures Can Open Doors")
		add("vjbase.menu.snpc.options.togglehumansdropweapon", "Humans Drop Weapon On Death")
		add("vjbase.menu.snpc.options.togglehumanscanjump", "Humans Can Jump")
		add("vjbase.menu.snpc.options.toggleplydroppedweapons", "Players Can Pick Up Dropped Weapons")
		
		add("vjbase.menu.snpc.settings", "Settings")
		add("vjbase.menu.snpc.settings.label1", "AI Settings:")
		add("vjbase.menu.snpc.settings.togglewandering", "Disable Wandering When Idle")
		add("vjbase.menu.snpc.settings.togglechasingenemy", "Disable Chasing Enemy")
		add("vjbase.menu.snpc.settings.label2", "Use this setting with caution, it can break a lot of things!")
		add("vjbase.menu.snpc.settings.togglemedics", "Disable Medic SNPCs")
		add("vjbase.menu.snpc.settings.togglefollowplayer", "Disable Following Player")
		add("vjbase.menu.snpc.settings.label3", "Example: When you press 'E' on a SNPC and they follow you")
		add("vjbase.menu.snpc.settings.toggleallies", "Disable Alliance (No Allies!)")
		add("vjbase.menu.snpc.settings.togglebecomeenemytoply", "Disable Allies Becoming Enemy")
		add("vjbase.menu.snpc.settings.toggleproppush", "Disable Prop Pushing (Creatures)")
		add("vjbase.menu.snpc.settings.togglepropattack", "Disable Prop Attacking (Creatures)")
		add("vjbase.menu.snpc.settings.togglescarednade", "Disable Humans Running from Grenades")
		add("vjbase.menu.snpc.settings.togglereloading", "Disable Weapon Reloading")
		add("vjbase.menu.snpc.settings.label4", "Attack Settings:")
		add("vjbase.menu.snpc.settings.togglemelee", "Disable Melee Attacks")
		add("vjbase.menu.snpc.settings.togglerange", "Disable Range Attacks")
		add("vjbase.menu.snpc.settings.toggleleap", "Disable Leap Attacks (Creatures)")
		add("vjbase.menu.snpc.settings.togglethrownade", "Disable Grenade Attacks (Humans)")
		add("vjbase.menu.snpc.settings.toggleweapons", "Disable Weapons (Humans)")
		add("vjbase.menu.snpc.settings.label5", "Humans will not be able to use weapons!")
		add("vjbase.menu.snpc.settings.togglemeleedsp", "Disable DSP Effect On Heavy Melee Damages")
		add("vjbase.menu.snpc.settings.toggleslowplayer", "Disable Players Slowing Down on Melee Attack")
		add("vjbase.menu.snpc.settings.togglebleedonmelee", "Disable Players/NPCs Bleeding on Melee Attack")
		add("vjbase.menu.snpc.settings.label6", "Miscellaneous Settings:")
		add("vjbase.menu.snpc.settings.toggleidleparticles", "Disable Idle Particles and Effects")
		add("vjbase.menu.snpc.settings.label7", "Disabling this can help with performance")
		add("vjbase.menu.snpc.settings.togglesnpcchat", "Disable SNPC Chat")
		add("vjbase.menu.snpc.settings.label8", "For example: 'Scientist is now following you'")
		add("vjbase.menu.snpc.settings.label9", "Damage & Corpse Settings:")
		add("vjbase.menu.snpc.settings.toggleflinching", "Disable Flinching")
		add("vjbase.menu.snpc.settings.togglebleeding", "Disable Bleeding")
		add("vjbase.menu.snpc.settings.label10", "Disables blood particles, decals, blood pools etc.")
		add("vjbase.menu.snpc.settings.togglebloodpool", "Disable Blood Pools (On Death)")
		add("vjbase.menu.snpc.settings.togglegib", "Disable Gibbing")
		add("vjbase.menu.snpc.settings.label11", "Disabling this can help with performance")
		add("vjbase.menu.snpc.settings.togglegibdecals", "Disable Gib Decals")
		add("vjbase.menu.snpc.settings.togglegibdeathparticles", "Disable Gib/Death Particles and Effects")
		add("vjbase.menu.snpc.settings.toggledeathanim", "Disable Death Animation")
		add("vjbase.menu.snpc.settings.togglecorpses", "Disable Corpses")
		add("vjbase.menu.snpc.settings.label12", "Passive Settings:")
		add("vjbase.menu.snpc.settings.togglerunontouch", "Disable Running on Touch")
		add("vjbase.menu.snpc.settings.togglerunonhit", "Disable Running on Hit")
		
		add("vjbase.menu.snpc.sdsettings", "Sound Settings")
		add("vjbase.menu.snpc.sdsettings.toggleallsounds", "Disable All Sounds")
		add("vjbase.menu.snpc.sdsettings.togglesoundtrack", "Disable Sound Tracks")
		add("vjbase.menu.snpc.sdsettings.toggleidle", "Disable Idle Sounds")
		add("vjbase.menu.snpc.sdsettings.togglebreathing", "Disable Breathing Sounds")
		add("vjbase.menu.snpc.sdsettings.togglefootsteps", "Disable Footstep Sounds")
		add("vjbase.menu.snpc.sdsettings.toggleattacksounds", "Disable Melee Attack Sounds")
		add("vjbase.menu.snpc.sdsettings.togglemeleemiss", "Disable Melee Miss Sounds")
		add("vjbase.menu.snpc.sdsettings.togglerangeattack", "Disable Range Attack Sounds")
		add("vjbase.menu.snpc.sdsettings.togglealert", "Disable Alert Sounds")
		add("vjbase.menu.snpc.sdsettings.togglepain", "Disable Pain Sounds")
		add("vjbase.menu.snpc.sdsettings.toggledeath", "Disable Death Sounds")
		add("vjbase.menu.snpc.sdsettings.togglegibbing", "Disable Gibbing Sounds")
		add("vjbase.menu.snpc.sdsettings.label1", "Also applies to the sounds that play when a gib collides with something")
		add("vjbase.menu.snpc.sdsettings.togglemedic", "Disable Medic Sounds")
		add("vjbase.menu.snpc.sdsettings.togglefollowing", "Disable Following Sounds")
		add("vjbase.menu.snpc.sdsettings.togglecallhelp", "Disable Calling for Help Sounds")
		add("vjbase.menu.snpc.sdsettings.togglereceiveorder", "Disable Receiving Order Sounds")
		add("vjbase.menu.snpc.sdsettings.togglebecomeenemy", "Disable Become Enemy to Player Sounds")
		add("vjbase.menu.snpc.sdsettings.toggleplayersight", "Disable Player Sighting Sounds")
		add("vjbase.menu.snpc.sdsettings.label2", "Special sounds that play when a SNPC sees the player")
		add("vjbase.menu.snpc.sdsettings.toggledmgbyplayer", "Disable Damage By Player Sounds")
		add("vjbase.menu.snpc.sdsettings.label3", "When the player shoots at a SNPC, usually friendly SNPCs")
		add("vjbase.menu.snpc.sdsettings.toggleleap", "Disable Leap Attack Sounds")
		add("vjbase.menu.snpc.sdsettings.toggleslowedplayer", "Disable Slowed Player Sounds")
		add("vjbase.menu.snpc.sdsettings.label4", "Sounds that play when the player is slowed down by melee attack")
		add("vjbase.menu.snpc.sdsettings.togglegrenade", "Disable Grenade Attack Sounds")
		add("vjbase.menu.snpc.sdsettings.togglegrenadesight", "Disable On Grenade Sight Sounds")
		add("vjbase.menu.snpc.sdsettings.togglesuppressing", "Disable Suppressing Call Out Sounds")
		add("vjbase.menu.snpc.sdsettings.togglereload", "Disable Reload Call Out Sounds")
		
		add("vjbase.menu.snpc.devsettings", "Developer Settings")
		add("vjbase.menu.snpc.devsettings.label1", "These settings are used when developing SNPCs.")
		add("vjbase.menu.snpc.devsettings.label2", "WARNING: Some of these options cause lag!")
		add("vjbase.menu.snpc.devsettings.toggledev", "Enable Developer Mode?")
		add("vjbase.menu.snpc.devsettings.label3", "This option must be enabled from here or through the context menu! (Required for the options below)")
		add("vjbase.menu.snpc.devsettings.printtouch", "Print On Touch (Console)")
		add("vjbase.menu.snpc.devsettings.printcurenemy", "Print Current Enemy (Console)")
		add("vjbase.menu.snpc.devsettings.printlastseenenemy", "Print 'LastSeenEnemy' time (Chat/Console)")
		add("vjbase.menu.snpc.devsettings.printonreset", "Print On Reset Enemy (Console)")
		add("vjbase.menu.snpc.devsettings.printonstopattack", "Print On Stopped Attacks (Console)")
		add("vjbase.menu.snpc.devsettings.printtakingcover", "Print Taking Cover (Console)")
		add("vjbase.menu.snpc.devsettings.printondamage", "Print On Damage (Console)")
		add("vjbase.menu.snpc.devsettings.printondeath", "Print On Death (Console)")
		add("vjbase.menu.snpc.devsettings.printweapon", "Print Current Weapon (Console)")
		add("vjbase.menu.snpc.devsettings.printammo", "Print Amount of Ammo (Console)")
		add("vjbase.menu.snpc.devsettings.printaccuracy", "Print Gun Accuracy (Console)")
		add("vjbase.menu.snpc.devsettings.cachedmodels", "Cached Models (Console)")
		
		add("vjbase.menu.snpc.consettings", "Controller Settings")
		add("vjbase.menu.snpc.consettings.label1", "Notice: These are client-side settings only!")
		add("vjbase.menu.snpc.consettings.label2", "How far or close the zoom changes every click.")
		add("vjbase.menu.snpc.consettings.displayhud", "Display HUD")
		add("vjbase.menu.snpc.consettings.zoomdistance", "Zoom Distance")
		add("vjbase.menu.snpc.consettings.displaydev", "Display Developer Entities")
		add("vjbase.menu.snpc.consettings.label3", "Key Bindings:")
		add("vjbase.menu.snpc.consettings.bind.header1", "Control")
		add("vjbase.menu.snpc.consettings.bind.header2", "Description")
		add("vjbase.menu.snpc.consettings.bind.clickmsg1", "Selected Key:")
		add("vjbase.menu.snpc.consettings.bind.clickmsg2", "Description:")
		add("vjbase.menu.snpc.consettings.bind.movement", "Movement (Supports 8-Way)")
		add("vjbase.menu.snpc.consettings.bind.exitcontrol", "Exit the Controller")
		add("vjbase.menu.snpc.consettings.bind.meleeattack", "Melee Attack")
		add("vjbase.menu.snpc.consettings.bind.rangeattack", "Range / Weapon Attack")
		add("vjbase.menu.snpc.consettings.bind.leaporgrenade", "Leap / Grenade Attack")
		add("vjbase.menu.snpc.consettings.bind.reloadweapon", "Reload Weapon")
		add("vjbase.menu.snpc.consettings.bind.togglebullseye", "Toggle Bullseye Tracking")
		add("vjbase.menu.snpc.consettings.bind.cameraup", "Move Camera Up")
		add("vjbase.menu.snpc.consettings.bind.cameradown", "Move Camera Down")
		add("vjbase.menu.snpc.consettings.bind.cameraforward", "Move Camera Forward")
		add("vjbase.menu.snpc.consettings.bind.camerabackward", "Move Camera Backward")
		add("vjbase.menu.snpc.consettings.bind.cameraleft", "Move Camera Left")
		add("vjbase.menu.snpc.consettings.bind.cameraright", "Move Camera Right")
		add("vjbase.menu.snpc.consettings.bind.resetzoom", "Reset Zoom")
		
		-- Weapon Client Settings
		add("vjbase.menu.clweapon", "Client Settings")
		add("vjbase.menu.clweapon.notice", "Notice: These settings are client, meaning it won't change for other people!")
		add("vjbase.menu.clweapon.togglemuzzle", "Disable Muzzle Flash")
		add("vjbase.menu.clweapon.togglemuzzlelight", "Disable Muzzle Flash Dynamic Light")
		add("vjbase.menu.clweapon.togglemuzzle.label", "Disabling muzzle flash will also disable this")
		add("vjbase.menu.clweapon.togglemuzzlesmoke", "Disable Muzzle Smoke")
		add("vjbase.menu.clweapon.togglemuzzleheatwave", "Disable Muzzle Heat Wave")
		add("vjbase.menu.clweapon.togglemuzzlebulletshells", "Disable Bullet Shells")
		
		-- NPC Properties (C Menu)
		add("vjbase.menuproperties.control", "TAKE CONTROL")
		add("vjbase.menuproperties.guard", "Toggle Guarding")
		add("vjbase.menuproperties.wander", "Toggle Wandering")
		add("vjbase.menuproperties.medic", "Make Medic (Toggle)")
		add("vjbase.menuproperties.allyme", "Ally To Me")
		add("vjbase.menuproperties.hostileme", "Hostile To Me")
		add("vjbase.menuproperties.slay", "Slay")
		add("vjbase.menuproperties.gib", "Gib (If Valid)")
		add("vjbase.menuproperties.devmode", "Toggle Developer Mode")
		
		-- Tools
		add("tool.vjstool.menu.tutorialvideo", "Tutorial Video")
		add("tool.vjstool.menu.label.recommendation", "Recommended to use this tool only for VJ Base SNPCs.")
		
		add("tool.vjstool_bullseye.name", "NPC Bullseye")
		add("tool.vjstool_bullseye.desc", "Creates a bullseye that NPCs will target")
		add("tool.vjstool_bullseye.left", "Create a bullseye")
		add("tool.vjstool_bullseye.menu.help1", "Press USE on the entity to activate/deactivate.")
		add("tool.vjstool_bullseye.menu.help2", "When deactivated, NPCs will no longer target it.")
		add("tool.vjstool_bullseye.menu.label1", "Select Movement Type")
		add("tool.vjstool_bullseye.menu.label2", "Model Directory")
		add("tool.vjstool_bullseye.menu.toggleusestatus", "Use Status Colors (Activated/Deactivated)")
		add("tool.vjstool_bullseye.menu.togglestartactivated", "Start Activated")
		
		add("tool.vjstool_entityscanner.name", "Entity Scanner")
		add("tool.vjstool_entityscanner.desc", "Get information about an entity")
		add("tool.vjstool_entityscanner.left", "Print information about the entity in console")
		add("tool.vjstool_entityscanner.label", "Prints information about any selected entity, it's printed in the console.")
		
		add("tool.vjstool_healthmodifier.name", "Health Modifier")
		add("tool.vjstool_healthmodifier.desc", "Modify the health of an entity")
		add("tool.vjstool_healthmodifier.left", "Set health")
		add("tool.vjstool_healthmodifier.right", "Set health & max health")
		add("tool.vjstool_healthmodifier.reload", "Heal the entity to its max health")
		add("tool.vjstool_healthmodifier.adminonly", "Only admins can modify or heal another player's health.")
		add("tool.vjstool_healthmodifier.sliderhealth", "Health")
		add("tool.vjstool_healthmodifier.label1", "Following are only for VJ Base SNPCs:")
		add("tool.vjstool_healthmodifier.togglegodmode", "God Mode (invincible)")
		add("tool.vjstool_healthmodifier.togglehealthregen", "Enable Health Regeneration")
		add("tool.vjstool_healthmodifier.sliderhealthregenamt", "Regeneration Amount")
		add("tool.vjstool_healthmodifier.sliderhealthregendelay", "Regeneration Delay")
		
		add("tool.vjstool_notarget.name", "No Target")
		add("tool.vjstool_notarget.desc", "Setting no target will make all NPCs not see a certain entity")
		add("tool.vjstool_notarget.left", "Toggle no target to yourself")
		add("tool.vjstool_notarget.right", "Toggle no target to an NPC or player")
		add("tool.vjstool_notarget.label", "When a no target is enabled on an entity, NPCs will not target it!")
		
		add("tool.vjstool_npcequipment.name", "NPC Equipment")
		add("tool.vjstool_npcequipment.desc", "Modifies an NPC's equipment")
		add("tool.vjstool_npcequipment.left", "Change the NPC's equipment")
		add("tool.vjstool_npcequipment.right", "Remove the NPC's equipment")
		add("tool.vjstool_npcequipment.label", "Changes or removes an NPC's equipment.")
		add("tool.vjstool_npcequipment.selectedequipment", "Selected Equipment")
		add("tool.vjstool_npcequipment.print.doubleclick", "Double click to select a weapon.")
		add("tool.vjstool_npcequipment.print.weaponselected1", "Weapon")
		add("tool.vjstool_npcequipment.print.weaponselected2", "selected!")
		add("tool.vjstool_npcequipment.header1", "Name")
		add("tool.vjstool_npcequipment.header2", "Class")
		
		add("tool.vjstool_npcmover.name", "NPC Mover")
		add("tool.vjstool_npcmover.desc", "Move NPC(s), an NPC must first be selected")
		add("tool.vjstool_npcmover.left", "Select an NPC")
		add("tool.vjstool_npcmover.right", "Run to the location")
		add("tool.vjstool_npcmover.reload", "Walk to the location")
		add("tool.vjstool_npcmover.header1", "Name")
		add("tool.vjstool_npcmover.header2", "Class")
		add("tool.vjstool_npcmover.header3", "Information")
		add("tool.vjstool_npcmover.buttonunselectall", "Unselect All NPCs")
		add("tool.vjstool_npcmover.print.unselectedall", "Unselected all NPCs!")
		add("tool.vjstool_npcmover.print.unselectedall.error", "Nothing to unselect!")
		
		add("tool.vjstool_npcrelationship.name", "NPC Relationship Modifier")
		add("tool.vjstool_npcrelationship.desc", "Modify the relationship of entities")
		add("tool.vjstool_npcrelationship.left", "Apply the relationship table")
		add("tool.vjstool_npcrelationship.right", "Obtain the current classes")
		add("tool.vjstool_npcrelationship.reload", "Apply the relationship table to yourself")
		add("tool.vjstool_npcrelationship.label1", "Modifies the relationship of an NPC, basically how it feels towards another entity.")
		add("tool.vjstool_npcrelationship.header", "Class")
		add("tool.vjstool_npcrelationship.label2", "Press return to add the class.")
		add("tool.vjstool_npcrelationship.button.combine", "Insert Combine Class")
		add("tool.vjstool_npcrelationship.button.antlion", "Insert Antlion Class")
		add("tool.vjstool_npcrelationship.button.zombie", "Insert Zombie Class")
		add("tool.vjstool_npcrelationship.button.player", "Insert Player Class")
		add("tool.vjstool_npcrelationship.togglealliedply", "Allied with all player allies?")
		add("tool.vjstool_npcrelationship.label3", "Only applies for VJ Base SNPCs and requires the SNPC to have")
		add("tool.vjstool_npcrelationship.print.applied", "Applied the relationship class table on")
		
		add("tool.vjstool_npcspawner.name", "NPC Spawner")
		add("tool.vjstool_npcspawner.desc", "Creates a customizable spawner")
		add("tool.vjstool_npcspawner.left", "Create a spawner")
		add("tool.vjstool_npcspawner.right", "Create the entities once")
		add("tool.vjstool_npcspawner.selectednpc", "Selected NPC")
		add("tool.vjstool_npcspawner.spawnpos.forward", "Position | Forward")
		add("tool.vjstool_npcspawner.spawnpos.right", "Position | Right")
		add("tool.vjstool_npcspawner.spawnpos.up", "Position | Up")
		add("tool.vjstool_npcspawner.selectweapon", "Selected Weapon")
		add("tool.vjstool_npcspawner.button.updatelist", "Update List")
		add("tool.vjstool_npcspawner.label1", "Double click on an item to remove it.")
		add("tool.vjstool_npcspawner.header1", "Name")
		add("tool.vjstool_npcspawner.header2", "Position")
		add("tool.vjstool_npcspawner.header3", "Equipment")
		add("tool.vjstool_npcspawner.label2", "Extra Options")
		add("tool.vjstool_npcspawner.toggle.spawnsound", "Play NPC Spawning Sound?")
		add("tool.vjstool_npcspawner.nextspawntime", "Next Spawn Time")
		add("tool.vjstool_npcspawner.popup.header1", "Name")
		add("tool.vjstool_npcspawner.popup.header2", "Class")
		add("tool.vjstool_npcspawner.popup.header3", "Category")
		add("tool.vjstool_npcspawner.title1", "Double click to select an NPC.")
		add("tool.vjstool_npcspawner.title2", "Double click to select a weapon.")
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------ ///// WARNING: Don't touch anything above this line! \\\\\ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

		if conv == "armenian" then
			
		elseif conv == "russian" then ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
			-- General Menu (Used everywhere)
			add("vjbase.menu.general.default", "По умолчанию")
			add("vjbase.menu.general.admin.only", "Примечание: только администраторы могут использовать это меню.")
			add("vjbase.menu.general.admin.not", "Вы не являетесь администратором!")
			add("vjbase.menu.general.reset.everything", "Сбросить по умолчанию")
			add("vjbase.menu.general.snpc.warnfuture", "Предупреждение: будут затронуты только будущие созданные NPC!")
			add("vjbase.menu.general.snpc.creaturesettings", "Настройки создания:")
			add("vjbase.menu.general.snpc.humansettings", "Человеческие установки:")
			
			-- Menu Tabs
			add("vjbase.menu.tabs.mainmenu", "Главное меню")
			add("vjbase.menu.tabs.settings.snpc", "Настройки SNPC")
			add("vjbase.menu.tabs.settings.weapon", "Настройки оружия")
			add("vjbase.menu.tabs.settings.hud", "Настройки HUD")
			add("vjbase.menu.tabs.tools", "Инструменты")
			add("vjbase.menu.tabs.configures.snpc", "Конфигурации SNPC")
			
			-- Main Menu
			add("vjbase.menu.cleanup", "Очистка")
			add("vjbase.menu.cleanup.everything", "Очистить всё")
			add("vjbase.menu.cleanup.stopsounds", "Остановить все звуки")
			add("vjbase.menu.cleanup.remove.vjnpcs", "Убрать все VJ SNPCs")
			add("vjbase.menu.cleanup.remove.npcs", "Убрать все (S)NPCs")
			add("vjbase.menu.cleanup.remove.spawners", "Убрать все спавнеры")
			add("vjbase.menu.cleanup.remove.corpses", "Убрать все тела")
			add("vjbase.menu.cleanup.remove.vjgibs", "Убрать все VJ Gibs")
			add("vjbase.menu.cleanup.remove.groundweapons", "Убрать всё оружие на земле")
			add("vjbase.menu.cleanup.remove.props", "Убрать все пропы")
			add("vjbase.menu.cleanup.remove.decals", "Убрать все декали")
			add("vjbase.menu.cleanup.remove.allweapons", "Убрать всё своё оружие")
			add("vjbase.menu.cleanup.remove.allammo", "Убрать все свои боеприпасы")
			
			add("vjbase.menu.helpsupport", "Контакты и поддержка")
			add("vjbase.menu.helpsupport.reportbug", "Сообщить о проблеме")
			add("vjbase.menu.helpsupport.suggestion", "Предложить что-нибудь")
			add("vjbase.menu.helpsupport.discord", "Discord создателя!")
			add("vjbase.menu.helpsupport.steam", "Steam создателя!")
			add("vjbase.menu.helpsupport.youtube", "Подписка на YouTube!")
			add("vjbase.menu.helpsupport.twtiter", "Подписка на Twitter!")
			add("vjbase.menu.helpsupport.patron", "Поддержите меня на Patron!")
			add("vjbase.menu.helpsupport.label1", "Перейдите по одной из этих ссылок, чтобы получить информацию об обновлениях моих аддонов!")
			add("vjbase.menu.helpsupport.label2", "Пожертвования помогают и поощряют меня продолжать делать/обновлять аддоны! Спасибо!")
			add("vjbase.menu.helpsupport.thanks", "Спасибо за вашу поддержку!")
			
			add("vjbase.menu.svsettings", "Административные настройки")
			add("vjbase.menu.svsettings.label", "ВНИМАНИЕ: НЕКОТОРЫЕ НАСТРОЙКИ ЯВЛЯЮТСЯ ЧИТЕРСКИМИ!")
			add("vjbase.menu.svsettings.admin.npcproperties", "Ограничивает свойства SNPC только администраторами")
			add("vjbase.menu.svsettings.noclip", "Позволить NoClip")
			add("vjbase.menu.svsettings.weapons", "Позволить оружие")
			add("vjbase.menu.svsettings.pvp", "Позволить PvP")
			add("vjbase.menu.svsettings.godmode", "God Mode (Для всех)")
			add("vjbase.menu.svsettings.bonemanip.npcs", "Манипулировать костями NPCs")
			add("vjbase.menu.svsettings.bonemanip.players", "Манипулировать костями моделей игроков")
			add("vjbase.menu.svsettings.bonemanip.others", "Манипулировать костями иных объектов")
			add("vjbase.menu.svsettings.timescale.general", "Общий TimeScale")
			add("vjbase.menu.svsettings.timescale.physics", "Физический TimeScale")
			add("vjbase.menu.svsettings.gravity", "Общая гравитация")
			add("vjbase.menu.svsettings.maxentsprops", "Максимум пропов/энтити:")
			
			add("vjbase.menu.clsettings", "Настройки клиента")
			add("vjbase.menu.clsettings.label", "Используйте это меню для настройки параметров клиента, администраторы сервера не могут изменить эти параметры!")
			add("vjbase.menu.clsettings.labellang", "Выбор языка...")
			add("vjbase.menu.clsettings.notify.lang", "Язык VJ Base установлен на:")
			
			add("vjbase.menu.info", "Информация")
			
			add("vjbase.menu.plugins", "Установленные плагины")
			add("vjbase.menu.plugins.label", "Список установленных плагинов VJ Base.")
			add("vjbase.menu.plugins.version", "Версия:")
			add("vjbase.menu.plugins.totalplugins", "Всего плагинов:")
			add("vjbase.menu.plugins.header1", "Название")
			add("vjbase.menu.plugins.header2", "Тип")
			add("vjbase.menu.plugins.notfound", "Плагины не найдены.")
			add("vjbase.menu.plugins.changelog", "Список изменений")
			add("vjbase.menu.plugins.makeaddon", "Хотите сделать аддон? Нажмите сюда!")
			
			-- SNPC Menus
			add("vjbase.menu.snpc.options", "Опции")
			add("vjbase.menu.snpc.options.difficulty.header", "Выбрать сложность:")
			add("vjbase.menu.snpc.options.difficulty.neanderthal", "Неандерталец | -99% Здоровья и Урона")
			add("vjbase.menu.snpc.options.difficulty.childs_play", "Детская игра | -75% Здоровья и Урона")
			add("vjbase.menu.snpc.options.difficulty.easy", "Легко | -50% Здоровья и Урона")
			add("vjbase.menu.snpc.options.difficulty.normal", "Нормально | Стандартно Здоровья и Урона")
			add("vjbase.menu.snpc.options.difficulty.hard", "Трудно | +50% Здоровья и Урона")
			add("vjbase.menu.snpc.options.difficulty.insane", "Безумие | +100% Здоровья и Урона")
			add("vjbase.menu.snpc.options.difficulty.impossible", "Невозможно | +150% Здоровья и Урона")
			add("vjbase.menu.snpc.options.difficulty.nightmare", "Кошмар | +250% Здоровья и Урона")
			add("vjbase.menu.snpc.options.difficulty.hell_on_earth", "Ад на Земле | +350% Здоровья и Урона")
			add("vjbase.menu.snpc.options.difficulty.total_annihilation", "Тотальная Аннигиляция | +500% Здоровья и Урона")
			add("vjbase.menu.snpc.options.label1", "Настройки отношшений:")
			add("vjbase.menu.snpc.options.togglefriendlyantlion", "Antlion Дружелюбный")
			add("vjbase.menu.snpc.options.togglefriendlycombine", "Combine Дружелюбный")
			add("vjbase.menu.snpc.options.togglefriendlyplayer", "Игрок Дружелюбный")
			add("vjbase.menu.snpc.options.togglefriendlyzombie", "Zombie Дружелюбный")
			add("vjbase.menu.snpc.options.togglefriendlyvj", "VJ Base Дружелюбный")
			add("vjbase.menu.snpc.options.label2", "Все VJ SNPCs будут союзниками!")
			add("vjbase.menu.snpc.options.label3", "Опции тел и здоровья:")
			add("vjbase.menu.snpc.options.corpselimit", "Лимит тел, По умолчанию:32")
			add("vjbase.menu.snpc.options.label4", "Лимит тел, когда 'Удержание тел' выключено")
			add("vjbase.menu.snpc.options.toggleundocorpses", "Отмена тел (клавиша отмены)")
			add("vjbase.menu.snpc.options.togglecorpsefade", "Исчезновение тел")
			add("vjbase.menu.snpc.options.corpsefadetime", "Время исчезновения тела")
			add("vjbase.menu.snpc.options.label5", "Итого: 600 секунд (10 минут)")
			add("vjbase.menu.snpc.options.togglegibcollision", "Коллизия Gibs")
			add("vjbase.menu.snpc.options.togglefadegibs", "Исчезновение Gibs")
			add("vjbase.menu.snpc.options.gibfadetime", "Время исчезновения Gib")
			add("vjbase.menu.snpc.options.label6", "По умолчанию: 30 | всего: 600 секунд (10 минут)")
			add("vjbase.menu.snpc.options.togglesnpcgodmode", "God Mode (Они не понесут никакого ущерба.)")
			add("vjbase.menu.snpc.options.health", "Здоровье:")
			add("vjbase.menu.snpc.options.defaulthealth", "0 = Здоровье по умолчанию (максимум 9 цифр!)")
			add("vjbase.menu.snpc.options.label7", "Опции ИИ:")
			add("vjbase.menu.snpc.options.toggleknowenemylocation", "Всегда знать расположение врага")
			add("vjbase.menu.snpc.options.sightdistance", "Расстояние видимости:")
			add("vjbase.menu.snpc.options.label8", "У каждого NPC есть своя дистанция, но это сделает их всех одинаковыми, так что используйте ее осторожно! (0 = Оригинал / среднее значение : 10k)")
			add("vjbase.menu.snpc.options.processtime", "Время процесса")
			add("vjbase.menu.snpc.options.whatisprocesstime", "Что такое 'Время процесса'?")
			add("vjbase.menu.snpc.options.label9", "По умолчанию: 1 / меньшее число вызывает большую задержку (лаги)!")
			add("vjbase.menu.snpc.options.label10", "Другие опции:")
			add("vjbase.menu.snpc.options.togglegmoddecals", "Использовать текущие декали крови Garry's Mod'а")
			add("vjbase.menu.snpc.options.label11", "Цвета, которые не являются желтыми или красными, не изменятся!")
			add("vjbase.menu.snpc.options.toggleitemdrops", "Дроп предметов при смерти")
			add("vjbase.menu.snpc.options.toggleshowhudonkilled", "Показать HUD-дисплей при убийстве SNPC (вверху справа)")
			add("vjbase.menu.snpc.options.toggleaddfrags", "Добавить очки на табло игрока, когда он убит")
			add("vjbase.menu.snpc.options.togglecreatureopendoor", "Существа могут открывать ддвери")
			add("vjbase.menu.snpc.options.togglehumansdropweapon", "Люди бросают оружие при смерти")
			add("vjbase.menu.snpc.options.togglehumanscanjump", "Люди могут прыгать")
			add("vjbase.menu.snpc.options.toggleplydroppedweapons", "Игроки могут подбирать упавшее оружие")
			
			add("vjbase.menu.snpc.settings", "Настройки")
			add("vjbase.menu.snpc.settings.label1", "Настройки ИИ:")
			add("vjbase.menu.snpc.settings.togglewandering", "Отключить блуждание в режиме ожидания")
			add("vjbase.menu.snpc.settings.togglechasingenemy", "Отключить преследование врага")
			add("vjbase.menu.snpc.settings.label2", "Используйте этот параметр с осторожностью, он может сломать много вещей!")
			add("vjbase.menu.snpc.settings.togglemedics", "Отключить медиков SNPCs")
			add("vjbase.menu.snpc.settings.togglefollowplayer", "Отключить следование за игроком")
			add("vjbase.menu.snpc.settings.label3", "Пример: когда вы нажимаете 'У' на SNPC, они следуют за Вами")
			add("vjbase.menu.snpc.settings.toggleallies", "Отключить альянс (Нет союзников!)")
			add("vjbase.menu.snpc.settings.togglebecomeenemytoply", "Отключить союзников, став врагом")
			add("vjbase.menu.snpc.settings.toggleproppush", "Отключить толкание пропов (Существ)")
			add("vjbase.menu.snpc.settings.togglepropattack", "Отключить атаку пропов (Существ)")
			add("vjbase.menu.snpc.settings.togglescarednade", "Отключить избегание гранат людьми")
			add("vjbase.menu.snpc.settings.togglereloading", "Отключить перезарядку оружия")
			add("vjbase.menu.snpc.settings.label4", "Настройки атаки:")
			add("vjbase.menu.snpc.settings.togglemelee", "Выключить атаку в ближнем бою")
			add("vjbase.menu.snpc.settings.togglerange", "Выключить атаку в дальнем бою")
			add("vjbase.menu.snpc.settings.toggleleap", "Отключить атаку в прыжке (Существа)")
			add("vjbase.menu.snpc.settings.togglethrownade", "Отключить атаку гранатами (Люди)")
			add("vjbase.menu.snpc.settings.toggleweapons", "Отключить оружие (Люди)")
			add("vjbase.menu.snpc.settings.label5", "Люди не смогут использовать оружие!")
			add("vjbase.menu.snpc.settings.togglemeleedsp", "Отключить эффект DSP на тяжелые повреждения ближнего боя")
			add("vjbase.menu.snpc.settings.toggleslowplayer", "Отключить замедление игроков при атаке ближнего боя")
			add("vjbase.menu.snpc.settings.togglebleedonmelee", "Отключить истекание кровью в результате атак ближнего боя игроков/NPC")
			add("vjbase.menu.snpc.settings.label6", "Прочие настройки:")
			add("vjbase.menu.snpc.settings.toggleidleparticles", "Отключить неработающие частицы и эффекты")
			add("vjbase.menu.snpc.settings.label7", "Отключение этого пункта может увеличить производительность")
			add("vjbase.menu.snpc.settings.togglesnpcchat", "Выключить чат SNPC")
			add("vjbase.menu.snpc.settings.label8", "Например: 'Ученый теперь следует за вами'.")
			add("vjbase.menu.snpc.settings.label9", "Настройки тел и урона:")
			add("vjbase.menu.snpc.settings.toggleflinching", "Отключить вздрагивание")
			add("vjbase.menu.snpc.settings.togglebleeding", "Отключить кровотечение")
			add("vjbase.menu.snpc.settings.label10", "Отключает частицы крови, декали, лужи крови и т. д.")
			add("vjbase.menu.snpc.settings.togglebloodpool", "Отключить лужи крови (при смерти)")
			add("vjbase.menu.snpc.settings.togglegib", "Отключить Gibbing")
			add("vjbase.menu.snpc.settings.label11", "Отключение этого пункта может увеличить производительность")
			add("vjbase.menu.snpc.settings.togglegibdecals", "Отключить декали Gib")
			add("vjbase.menu.snpc.settings.togglegibdeathparticles", "Отключить частицы и эффекты при Gib/Смерти")
			add("vjbase.menu.snpc.settings.toggledeathanim", "Выключить анимацию смерти")
			add("vjbase.menu.snpc.settings.togglecorpses", "Выключить тела")
			add("vjbase.menu.snpc.settings.label12", "Пассивные настройки:")
			add("vjbase.menu.snpc.settings.togglerunontouch", "Выключить избегание при касании")
			add("vjbase.menu.snpc.settings.togglerunonhit", "Выключить избегание при попадании")
			
			add("vjbase.menu.snpc.sdsettings", "Настройки звука")
			add("vjbase.menu.snpc.sdsettings.toggleallsounds", "Отключить все звуки")
			add("vjbase.menu.snpc.sdsettings.togglesoundtrack", "Отключить звуковые дорожки")
			add("vjbase.menu.snpc.sdsettings.toggleidle", "Отключить звуки повреждений")
			add("vjbase.menu.snpc.sdsettings.togglebreathing", "Отключить звуки дыхания")
			add("vjbase.menu.snpc.sdsettings.togglefootsteps", "Отключить звуки шагов")
			add("vjbase.menu.snpc.sdsettings.toggleattacksounds", "Отключить звуки атаки в ближнем бою")
			add("vjbase.menu.snpc.sdsettings.togglemeleemiss", "Отключить звуки промахов в ближнем бою")
			add("vjbase.menu.snpc.sdsettings.togglerangeattack", "Отключить звуки атак в дальнем бою")
			add("vjbase.menu.snpc.sdsettings.togglealert", "Отключить звуки оповещения")
			add("vjbase.menu.snpc.sdsettings.togglepain", "Отключить звуки боли")
			add("vjbase.menu.snpc.sdsettings.toggledeath", "Отключить звуки смерти")
			add("vjbase.menu.snpc.sdsettings.togglegibbing", "Отключить Gib-звуки")
			add("vjbase.menu.snpc.sdsettings.label1", "Также относится к звукам, которые воспроизводятся, когда gib сталкивается с чем- то")
			add("vjbase.menu.snpc.sdsettings.togglemedic", "Отключить звуки медицины")
			add("vjbase.menu.snpc.sdsettings.togglefollowing", "Отключить звуки следования")
			add("vjbase.menu.snpc.sdsettings.togglecallhelp", "Отключить звуки просьб о помощи")
			add("vjbase.menu.snpc.sdsettings.togglereceiveorder", "Отключить звуки получения приказов")
			add("vjbase.menu.snpc.sdsettings.togglebecomeenemy", "Отключить звуки становления врагом для игрока")
			add("vjbase.menu.snpc.sdsettings.toggleplayersight", "Отключить звуки прицеливания игрока")
			add("vjbase.menu.snpc.sdsettings.label2", "Специальные звуки, которые воспроизводятся, когда SNPC видит игрока")
			add("vjbase.menu.snpc.sdsettings.toggledmgbyplayer", "Отключить звуки урона от игрока")
			add("vjbase.menu.snpc.sdsettings.label3", "Когда игрок стреляет в SNPC, обычно дружественные SNPC")
			add("vjbase.menu.snpc.sdsettings.toggleleap", "Отключить звуки атаки в прыжке")
			add("vjbase.menu.snpc.sdsettings.toggleslowedplayer", "Отключить звуки замедления игрока")
			add("vjbase.menu.snpc.sdsettings.label4", "Звуки, которые воспроизводятся, когда игрок замедляется в рукопашной атаке")
			add("vjbase.menu.snpc.sdsettings.togglegrenade", "Отключить звуки атаки гранатой")
			add("vjbase.menu.snpc.sdsettings.togglegrenadesight", "Отключить звуки обнаружения гранаты")
			add("vjbase.menu.snpc.sdsettings.togglesuppressing", "Отключить подавление звуков взрыва")
			add("vjbase.menu.snpc.sdsettings.togglereload", "Отключить перезагрузку звуков вызова")
			
			add("vjbase.menu.snpc.devsettings", "Настройки разработчика")
			add("vjbase.menu.snpc.devsettings.label1", "Эти настройки используются при разработке SNPC.")
			add("vjbase.menu.snpc.devsettings.label2", "Предупреждение: некоторые из этих опций вызывают задержку (лаги)!")
			add("vjbase.menu.snpc.devsettings.toggledev", "Включить режим разработчика?")
			add("vjbase.menu.snpc.devsettings.label3", "Эта опция должна быть включена здесь или через контекстное меню! (Требуется для следующих опций)")
			add("vjbase.menu.snpc.devsettings.printtouch", "Вывод на табло (Консоль)")
			add("vjbase.menu.snpc.devsettings.printcurenemy", "Вывод текущего врага (Консоль)")
			add("vjbase.menu.snpc.devsettings.printlastseenenemy", "Вывод времени 'LastSeenEnemy' (Чат/Консоль)")
			add("vjbase.menu.snpc.devsettings.printonreset", "Вывод на сброс проотивника (Консоль)")
			add("vjbase.menu.snpc.devsettings.printonstopattack", "Вывод на остановку атаки (Консоль)")
			add("vjbase.menu.snpc.devsettings.printtakingcover", "Вывод укрытия (Консоль)")
			add("vjbase.menu.snpc.devsettings.printondamage", "Вывод о повреждениях (Консоль)")
			add("vjbase.menu.snpc.devsettings.printondeath", "Вывод о смерти (Консоль)")
			add("vjbase.menu.snpc.devsettings.printweapon", "Вывод текущего оружия (Консоль)")
			add("vjbase.menu.snpc.devsettings.printammo", "Вывод количества патронов/боезапаса (Консоль)")
			add("vjbase.menu.snpc.devsettings.printaccuracy", "Вывод меткости оружия (Консоль)")
			add("vjbase.menu.snpc.devsettings.cachedmodels", "Кэшированные модели (Консоль)")
			
			add("vjbase.menu.snpc.consettings", "Настройки контроллера")
			add("vjbase.menu.snpc.consettings.label1", "Обратите внимание : это настройки только на стороне клиента!")
			add("vjbase.menu.snpc.consettings.label2", "Как далеко или близко масштаб изменяется с каждым щелчком мыши.")
			add("vjbase.menu.snpc.consettings.displayhud", "Экранный HUD")
			add("vjbase.menu.snpc.consettings.zoomdistance", "Дистанция изменения расстояния видимости")
			add("vjbase.menu.snpc.consettings.displaydev", "Отображение энтити разработчика")
			add("vjbase.menu.snpc.consettings.label3", "Привязка клавиш:")
			add("vjbase.menu.snpc.consettings.bind.header1", "Контроль")
			add("vjbase.menu.snpc.consettings.bind.header2", "Описание")
			add("vjbase.menu.snpc.consettings.bind.clickmsg1", "Выбранная кнопка:")
			add("vjbase.menu.snpc.consettings.bind.clickmsg2", "Описание:")
			add("vjbase.menu.snpc.consettings.bind.movement", "Движение (Поддерживает 8-Полосный Режим)")
			add("vjbase.menu.snpc.consettings.bind.exitcontrol", "Выход из Контроллера")
			add("vjbase.menu.snpc.consettings.bind.meleeattack", "Атака в ближнем бою")
			add("vjbase.menu.snpc.consettings.bind.rangeattack", "Атака в дальнем бою")
			add("vjbase.menu.snpc.consettings.bind.leaporgrenade", "Прыжок/Атака гранатой")
			add("vjbase.menu.snpc.consettings.bind.reloadweapon", "Перезарядка")
			add("vjbase.menu.snpc.consettings.bind.togglebullseye", "Переключение отслеживания трассеров")
			add("vjbase.menu.snpc.consettings.bind.cameraup", "Сдвинуть камеру вверх")
			add("vjbase.menu.snpc.consettings.bind.cameradown", "Сдвинуть камеру вниз")
			add("vjbase.menu.snpc.consettings.bind.cameraforward", "Сдвинуть камеру вперёд")
			add("vjbase.menu.snpc.consettings.bind.camerabackward", "Сдвинуть камеру назад")
			add("vjbase.menu.snpc.consettings.bind.cameraleft", "Сдвинуть камеру влево")
			add("vjbase.menu.snpc.consettings.bind.cameraright", "Сдвинуть камеру вправо")
			add("vjbase.menu.snpc.consettings.bind.resetzoom", "Сбросить изменения расстояния видимости")
			
			-- Weapon Client Settings
			add("vjbase.menu.clweapon", "Настройки клиента")
			add("vjbase.menu.clweapon.notice", "Обратите внимание : эти настройки являются клиентскими, то есть они не изменятся для других людей!")
			add("vjbase.menu.clweapon.togglemuzzle", "Отключить дульную вспышку")
			add("vjbase.menu.clweapon.togglemuzzlelight", "Отключить динамический свет дульной вспышки")
			add("vjbase.menu.clweapon.togglemuzzle.label", "Отключение дульной вспышки также отключит это")
			add("vjbase.menu.clweapon.togglemuzzlesmoke", "Отключить дульный дым")
			add("vjbase.menu.clweapon.togglemuzzleheatwave", "Отключить дульную тепловую волну")
			add("vjbase.menu.clweapon.togglemuzzlebulletshells", "Отключить дымку от выстрелов")
			
			-- NPC Properties (C Menu)
			add("vjbase.menuproperties.control", "Взять под контроль")
			add("vjbase.menuproperties.guard", "Назначить телохранителем")
			add("vjbase.menuproperties.wander", "Назначить патрульным")
			add("vjbase.menuproperties.medic", "Назначить медиком")
			add("vjbase.menuproperties.allyme", "Назначить союзником")
			add("vjbase.menuproperties.hostileme", "Назначить противником")
			add("vjbase.menuproperties.slay", "Убить")
			add("vjbase.menuproperties.gib", "Gib (Если допустимо)")
			add("vjbase.menuproperties.devmode", "Переключить на режим разработчика")
			
			-- Tools
			add("tool.vjstool.menu.tutorialvideo", "Обучающее видео")
			add("tool.vjstool.menu.label.recommendation", "Рекомендуется использовать этот инструмент только для VJ Base SNPC.")
			
			add("tool.vjstool_bullseye.name", "Зона прицеливания NPC")
			add("tool.vjstool_bullseye.desc", "Создает зону приценивания, куда будут целиться NPC")
			add("tool.vjstool_bullseye.left", "ЛКМ для создания зоны прицеливания")
			add("tool.vjstool_bullseye.menu.help1", "Нажмите USE, чтобы активировать/деактивировать.")
			add("tool.vjstool_bullseye.menu.help2", "Когда она деактивирована, NPC больше не будет нацеливаться в неё.")
			add("tool.vjstool_bullseye.menu.label1", "Выбрать тип движения")
			add("tool.vjstool_bullseye.menu.label2", "Каталог моделей")
			add("tool.vjstool_bullseye.menu.toggleusestatus", "Использовать цвета состояния (Активировать/Деактивировать)")
			add("tool.vjstool_bullseye.menu.togglestartactivated", "Включить 'Активированный'")
			
			add("tool.vjstool_entityscanner.name", "Сканер энтити")
			add("tool.vjstool_entityscanner.desc", "Получить информацию про энтити")
			add("tool.vjstool_entityscanner.left", "Щелкните левой кнопкой мыши, чтобы вывести информацию об энтити в консоли")
			add("tool.vjstool_entityscanner.label", "Выводит информацию о любом выбранном объекте, она выводится в консоли.")
			
			add("tool.vjstool_healthmodifier.name", "Модификатор здоровья")
			add("tool.vjstool_healthmodifier.desc", "Изменение здоровья объекта")
			add("tool.vjstool_healthmodifier.left", "Щелкните левой кнопкой мыши, чтобы установить показатель здоровья")
			add("tool.vjstool_healthmodifier.right", "Щелкните правой кнопкой мыши, чтобы установить здоровье и максимальное здоровье")
			add("tool.vjstool_healthmodifier.reload", "Клавиша перезарядки для исцеления сущности до ее максимального здоровья")
			add("tool.vjstool_healthmodifier.adminonly", "Только администраторы могут изменять или лечить здоровье другого игрока.")
			add("tool.vjstool_healthmodifier.sliderhealth", "Здоровье")
			add("tool.vjstool_healthmodifier.togglegodmode", "God Mode (Непобедимый)")
			add("tool.vjstool_healthmodifier.label", "В настоящее время только для VJ Base SNPCs.")
			
			add("tool.vjstool_notarget.name", "Режим 'Вне цели'")
			add("tool.vjstool_notarget.desc", "Режим 'Вне цели' приведет к тому, что все NPC не увидят определенного игрока или NPC")
			add("tool.vjstool_notarget.left", "Щелкните левой кнопкой мыши, чтобы переключить режим 'Вне цели' для себя")
			add("tool.vjstool_notarget.right", "Щелкните правой кнопкой мыши, чтобы переключить режим 'Вне цели' на текущего игрока или NPC")
			add("tool.vjstool_notarget.label", "Если на объекте включена функция 'Вне цели' , то NPC не будут ее атаковать!")
			
			add("tool.vjstool_npcequipment.name", "Снаряжение NPC")
			add("tool.vjstool_npcequipment.desc", "Меняет снаряжение NPC")
			add("tool.vjstool_npcequipment.left", "Щелкните левой кнопкой мыши, чтобы изменить снаряжение NPC")
			add("tool.vjstool_npcequipment.right", "Щелкните правой кнопкой мыши, чтобы удалить снаряжение NPC")
			add("tool.vjstool_npcequipment.label", "Изменить или удалить снаряжение NPC.")
			add("tool.vjstool_npcequipment.selectedequipment", "Выбрать снаряжение")
			add("tool.vjstool_npcequipment.print.doubleclick", "Двойной клик для выбора оружия.")
			add("tool.vjstool_npcequipment.print.weaponselected1", "Оружие")
			add("tool.vjstool_npcequipment.print.weaponselected2", "выбрано!")
			add("tool.vjstool_npcequipment.header1", "Название")
			add("tool.vjstool_npcequipment.header2", "Классификация")
			
			add("tool.vjstool_npcmover.name", "Управление движением NPC")
			add("tool.vjstool_npcmover.desc", "Передвижение NPC или группы NPC")
			add("tool.vjstool_npcmover.left", "Щелкните левой кнопкой мыши, чтобы выбрать")
			add("tool.vjstool_npcmover.right", "Щелкните правой кнопкой мыши, чтобы переместить(бегом)")
			add("tool.vjstool_npcmover.reload", "Щелкните кнопку перезарядки, чтобы переместить(шагом)")
			add("tool.vjstool_npcmover.header1", "Имя")
			add("tool.vjstool_npcmover.header2", "Классификация")
			add("tool.vjstool_npcmover.header3", "Информация")
			add("tool.vjstool_npcmover.buttonunselectall", "Отменить выбор всех NPC")
			add("tool.vjstool_npcmover.print.unselectedall", "Выбор всех NPC отменён!")
			add("tool.vjstool_npcmover.print.unselectedall.error", "Ничего не нужно снимать (нечего)!")
			
			add("tool.vjstool_npcrelationship.name", "Модификатор отношений NPC")
			add("tool.vjstool_npcrelationship.desc", "Изменить отношения NPC")
			add("tool.vjstool_npcrelationship.left", "Щелкните левой кнопкой мыши, чтобы применить отношение")
			add("tool.vjstool_npcrelationship.right", "Щелкните правой кнопкой мыши, чтобы получить текущие классы")
			add("tool.vjstool_npcrelationship.reload", "Нажмите Перезарядку, чтобы применить к себе")
			add("tool.vjstool_npcrelationship.label1", "Изменяет отношение NPC, в основном то, как он чувствует себя по отношению к другому объекту.")
			add("tool.vjstool_npcrelationship.header", "Класс")
			add("tool.vjstool_npcrelationship.label2", "Нажмите кнопку Return, чтобы добавить класс.")
			add("tool.vjstool_npcrelationship.button.combine", "Вставить класс Combine")
			add("tool.vjstool_npcrelationship.button.antlion", "Вставить класс Antlion")
			add("tool.vjstool_npcrelationship.button.zombie", "Вставить класс Zombie")
			add("tool.vjstool_npcrelationship.button.player", "Вставить класс Игрок")
			add("tool.vjstool_npcrelationship.togglealliedply", "Союз со всеми союзниками игроков?")
			add("tool.vjstool_npcrelationship.label3", "Применяется только для VJ Base SNPC и требуется, чтобы SNPC имелся")
			add("tool.vjstool_npcrelationship.print.applied", "Применить таблицу классов отношений на")
			
			add("tool.vjstool_npcspawner.name", "Спавнер (создатель) NPC")
			add("tool.vjstool_npcspawner.desc", "Создать спавнер")
			add("tool.vjstool_npcspawner.left", "Щелкните левой кнопкой мыши, чтобы создать спавнер")
			add("tool.vjstool_npcspawner.right", "Щелкните правой кнопкой мыши, чтобы создать NPC один раз")
			add("tool.vjstool_npcspawner.selectednpc", "Выбранный NPC")
			add("tool.vjstool_npcspawner.spawnpos.forward", "Позиция | Вперёд")
			add("tool.vjstool_npcspawner.spawnpos.right", "Позиция | Вправо")
			add("tool.vjstool_npcspawner.spawnpos.up", "Позиция | Вверх")
			add("tool.vjstool_npcspawner.selectweapon", "Выбранное оружие")
			add("tool.vjstool_npcspawner.button.updatelist", "Обновить список")
			add("tool.vjstool_npcspawner.label1", "Дважды щелкните элемент, чтобы удалить его.")
			add("tool.vjstool_npcspawner.header1", "Имя")
			add("tool.vjstool_npcspawner.header2", "Позиция")
			add("tool.vjstool_npcspawner.header3", "Экипировка")
			add("tool.vjstool_npcspawner.label2", "Экстра опции")
			add("tool.vjstool_npcspawner.toggle.spawnsound", "Проигрывать звук спавна NPC?")
			add("tool.vjstool_npcspawner.nextspawntime", "Время следующего спавна")
			add("tool.vjstool_npcspawner.popup.header1", "Название")
			add("tool.vjstool_npcspawner.popup.header2", "Классификация")
			add("tool.vjstool_npcspawner.popup.header3", "Категория")
			add("tool.vjstool_npcspawner.title1", "Дважды щелкните, чтобы выбрать NPC.")
			add("tool.vjstool_npcspawner.title2", "Дважды щелкните, чтобы выбрать оружие.")
			
		elseif conv == "german" then ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
			
		elseif conv == "french" then ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
			
		elseif conv == "lithuanian" then ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
			-- General Menu (Used everywhere)
			add("vjbase.menu.general.default", "Numatytas")
			add("vjbase.menu.general.admin.only", "Dėmesio: tik administratoriai gali naudotis šiuo meniu.")
			add("vjbase.menu.general.admin.not", "Jūs neesate administratorius!")
			add("vjbase.menu.general.reset.everything", "Nustatyti į numatytuosius nustatymus")
			add("vjbase.menu.general.snpc.warnfuture", "DĖMESIO: paveikti bus tik vėliau atspawn'inti veikėjai!")
			add("vjbase.menu.general.snpc.creaturesettings", "Būtybių nustatymai:")
			add("vjbase.menu.general.snpc.humansettings", "Žmonių nustatymai")
			-- Menu Tabs
			add("vjbase.menu.tabs.mainmenu", "Pagrindinis meniu")
			add("vjbase.menu.tabs.settings.snpc", "Kompiuterinių veikėjų nustatymai")
			add("vjbase.menu.tabs.settings.weapon", "Ginklų nustatymai")
			add("vjbase.menu.tabs.settings.hud", "HUD nustatymai")
			add("vjbase.menu.tabs.tools", "Įrankiai")
			add("vjbase.menu.tabs.configures.snpc", "Veikėjų konfiguracija")
			
			-- Main Menu
			add("vjbase.menu.cleanup", "Išvalyti")
			add("vjbase.menu.cleanup.everything", "Išvalyti viską")
			add("vjbase.menu.cleanup.stopsounds", "Sustabdyti visus garsus")
			add("vjbase.menu.cleanup.remove.vjnpcs", "Pašalinti tik „VJ“ kompiuterinius veikėjus")
			add("vjbase.menu.cleanup.remove.npcs", "Pašalinti visus kompiuterinius veikėjus")
			add("vjbase.menu.cleanup.remove.spawners", "Pašalinti spawner'ius")
			add("vjbase.menu.cleanup.remove.corpses", "Pašalinti visus lavonus")
			add("vjbase.menu.cleanup.remove.vjgibs", "Pašalinti ištaškytus vidaus organus")
			add("vjbase.menu.cleanup.remove.groundweapons", "Pašalinti visus gulinčius ginklus")
			add("vjbase.menu.cleanup.remove.props", "Pašalinti visus daiktus")
			add("vjbase.menu.cleanup.remove.decals", "Pašalinti aplinkos teršalus")
			add("vjbase.menu.cleanup.remove.allweapons", "Pašalinti visus savo ginklus")
			add("vjbase.menu.cleanup.remove.allammo", "Pašalinti visą savo amuniciją")
			
			add("vjbase.menu.helpsupport", "Kontaktai ir pagalba")
			add("vjbase.menu.helpsupport.reportbug", "Pranešti apie klaidas")
			add("vjbase.menu.helpsupport.suggestion", "Pasiūlyti ką nors")
			add("vjbase.menu.helpsupport.discord", "Prisijunkite prie mano Discord!")
			add("vjbase.menu.helpsupport.steam", "Prisijunkite prie mano Steam grupės!")
			add("vjbase.menu.helpsupport.youtube", "Prenumeruokite mane ant YouTube!")
			add("vjbase.menu.helpsupport.twitter", "Sekite mane ant Twitter!")
			add("vjbase.menu.helpsupport.patreon", "Aukokite mano Patreon!")
			add("vjbase.menu.helpsupport.label1", "Spūstelėkite vienas iš šių nuorodų, kad žinotumėte apie mano priedų atnaujinimus!")
			add("vjbase.menu.helpsupport.label2", "Aukos padeda ir skatina mane tęsti kurti/naujinti priedus! Ačiū!")
			add("vjbase.menu.helpsupport.thanks", "Ačiū už Jūsų palaikymą!")
			
			add("vjbase.menu.svsettings", "Administraciniai serverio nustatymai")
			add("vjbase.menu.svsettings.label", "DĖMESIO: KAI KURIEM NUSTATYMAM REIKALINGAS SV_CHEATS 1!")
			add("vjbase.menu.svsettings.admin.npcproperties", "Apriboti kompiuterinių veikėjų savybių keitimą tik administratoriams")
			add("vjbase.menu.svsettings.noclip", "Leisti NoClip'ą")
			add("vjbase.menu.svsettings.weapons", "Leisti ginklus")
			add("vjbase.menu.svsettings.pvp", "Leisti PvP")
			add("vjbase.menu.svsettings.godmode", "Nemirtingumas (visiem)")
			add("vjbase.menu.svsettings.bonemanip.npcs", "Veikėjų kaulų manipuliacija")
			add("vjbase.menu.svsettings.bonemanip.players", "Žaidėjų kaulų manipuliacija")
			add("vjbase.menu.svsettings.bonemanip.others", "Kitų kaulų manipuliacija")
			add("vjbase.menu.svsettings.timescale.general", "Bendroji laiko skalė")
			add("vjbase.menu.svsettings.timescale.physics", "Fizikinė laiko skalė")
			add("vjbase.menu.svsettings.gravity", "Bendra gravitacija")
			add("vjbase.menu.svsettings.maxentsprops", "Maksimalus daiktų/objektų skaičius:")
			
			add("vjbase.menu.clsettings", "Klientų nustatymai")
			add("vjbase.menu.clsettings.label", "Naudokites šiuo meniu, kad nustatytumet savo nustatymus. Serveriai jų pakeisti negali.")
			add("vjbase.menu.clsettings.labellang", "Kalbos pasirinkimas...")
			add("vjbase.menu.clsettings.notify.lang", "„VJ Base“ kalba nustatyta į:")
			
			add("vjbase.menu.info", "Informacija")
			
			add("vjbase.menu.plugins", "Instaliuoti priedai")
			add("vjbase.menu.plugins.label", "Instaliuotų „VJ Base“ priedų sąrašas")
			add("vjbase.menu.plugins.version", "Versija:")
			add("vjbase.menu.plugins.totalplugins", "Priedų skaičius:")
			add("vjbase.menu.plugins.header1", "Pavadinimas")
			add("vjbase.menu.plugins.header2", "Tipas")
			add("vjbase.menu.plugins.notfound", "Nerasta jokių priedų.")
			add("vjbase.menu.plugins.changelog", "Pakeitimų sąrašas")
			add("vjbase.menu.plugins.makeaddon", "Norite sukurti priedą? Spūstelėkite čia!")
			
			-- SNPC Menus
			add("vjbase.menu.snpc.options", "Pasirenkami parametrai")
			add("vjbase.menu.snpc.options.difficulty.header", "Pasirinkite sunkumą:")
			add("vjbase.menu.snpc.options.difficulty.neanderthal", "Neandertaliečių | -99% sveikatos ir žalos")
			add("vjbase.menu.snpc.options.difficulty.childs_play", "Vaikų žaidimas | -75% sveikatos ir žalos")
			add("vjbase.menu.snpc.options.difficulty.easy", "Lengvas | -50% sveikatos ir žalos")
			add("vjbase.menu.snpc.options.difficulty.normal", "Numatytas | Originali sveikata ir žala")
			add("vjbase.menu.snpc.options.difficulty.hard", "Sunkus | +50% sveikatos ir žalos")
			add("vjbase.menu.snpc.options.difficulty.insane", "Beprotiškas | +100% sveikatos ir žalos")
			add("vjbase.menu.snpc.options.difficulty.impossible", "Neįmanomas | +150% sveikatos ir žalos")
			add("vjbase.menu.snpc.options.difficulty.nightmare", "Košmaras | +250% sveikatos ir žalos")
			add("vjbase.menu.snpc.options.difficulty.hell_on_earth", "Pragaras Žemėje | +350% sveikatos ir žalos")
			add("vjbase.menu.snpc.options.difficulty.total_annihilation", "Visiškas sunaikinimas | +500% sveikatos ir žalos")
			add("vjbase.menu.snpc.options.label1", "Santykių nustatymai:")
			add("vjbase.menu.snpc.options.togglefriendlyantlion", "Draugiški antlionams")
			add("vjbase.menu.snpc.options.togglefriendlycombine", "Draugiški „Combine“ imperijai")
			add("vjbase.menu.snpc.options.togglefriendlyplayer", "Draugiški žaidėjam")
			add("vjbase.menu.snpc.options.togglefriendlyzombie", "Draugiški zombiam")
			add("vjbase.menu.snpc.options.togglefriendlyvj", "Draugiški „VJ Base“ veikėjam")
			add("vjbase.menu.snpc.options.label2", "Visi „VJ“ veikėjai viens kito nepuls!")
			add("vjbase.menu.snpc.options.label3", "Lavonų ir sveikatos nustatymai:")
			add("vjbase.menu.snpc.options.corpselimit", "Lavonų limitas, numatytas sk.:32")
			add("vjbase.menu.snpc.options.label4", "Lavonų limitas kai lavonų išlaikymas yra išjungtas")
			add("vjbase.menu.snpc.options.toggleundocorpses", "Panaikinami lavonai (Panaikinimo mygtukas)")
			add("vjbase.menu.snpc.options.togglecorpsefade", "Išnykstantys lavonai")
			add("vjbase.menu.snpc.options.corpsefadetime", "Lavonų išnykimo laikas")
			add("vjbase.menu.snpc.options.label5", "Maks.: 600 sekundžių (10 minučių)")
			add("vjbase.menu.snpc.options.togglegibcollision", "Prisilietimai prie vidaus organų")
			add("vjbase.menu.snpc.options.togglefadegibs", "Išnykstantys vidaus organai")
			add("vjbase.menu.snpc.options.gibfadetime", "Vidaus organų išnykimo laikas")
			add("vjbase.menu.snpc.options.label6", "Numatytas sk.: 30 | Maks.: 600 sekundžių (10 minučių)")
			add("vjbase.menu.snpc.options.togglesnpcgodmode", "Nemirtingumas (Negaus jokios žalos)")
			add("vjbase.menu.snpc.options.health", "Sveikata:")
			add("vjbase.menu.snpc.options.defaulthealth", "0 = Numatytas sk. (Maks. 9 skaičiai!)")
			add("vjbase.menu.snpc.options.label7", "Mąstymo nustatymai:")
			add("vjbase.menu.snpc.options.toggleknowenemylocation", "Visą laiką žino priešo vietą")
			add("vjbase.menu.snpc.options.sightdistance", "Regėjimo distancija:")
			add("vjbase.menu.snpc.options.label8", "Kiekvienas kompiuterinis veikėjas turi tam tikrą numatytą regėjimo distancija, bet šis nustatymas juos padarys vienodus. (0 = Originalus | Vid.: 10 tūkst.)")
			add("vjbase.menu.snpc.options.processtime", "Galvojimo laikas")
			add("vjbase.menu.snpc.options.whatisprocesstime", "Kas yra galvojimo laikas")
			add("vjbase.menu.snpc.options.label9", "Numatytas: 1 | Mažesnis skaičius lemia didesnį žaidimo trūkčiojimą!")
			add("vjbase.menu.snpc.options.label10", "Įvairūs kiti nustatymai:")
			add("vjbase.menu.snpc.options.togglegmoddecals", "Naudoti numatytą „Garry's Mod“ kraują")
			add("vjbase.menu.snpc.options.label11", "Spalvos, kurios nėra geltonos arba raudonos, nepasikeis!")
			add("vjbase.menu.snpc.options.toggleitemdrops", "Daiktų išmetimas mirties atveju")
			add("vjbase.menu.snpc.options.toggleshowhudonkilled", "Rodyti HUD informaciją kai kompiuterinis veikėjas miršta")
			add("vjbase.menu.snpc.options.toggleaddfrags", "Pridėti taškų žaidėjam į švieslentę, kai nužudomi veikėjai")
			add("vjbase.menu.snpc.options.togglecreatureopendoor", "Būtybės gali atidaryti duris")
			add("vjbase.menu.snpc.options.togglehumansdropweapon", "Žmonės mirties atveju išmeta turimą ginklą")
			add("vjbase.menu.snpc.options.togglehumanscanjump", "Žmonės gali pašokti")
			add("vjbase.menu.snpc.options.toggleplydroppedweapons", "Žaidėjai gali paimti išmestus ginklus")
			
			add("vjbase.menu.snpc.settings", "Nustatymai")
			add("vjbase.menu.snpc.settings.label1", "Papildomi veikėjų logikos nustatymai:")
			add("vjbase.menu.snpc.settings.togglewandering", "Išjungti klaidžiojimą ramybės būsenoje")
			add("vjbase.menu.snpc.settings.togglechasingenemy", "Išjungti priešo gaudymą")
			add("vjbase.menu.snpc.settings.label2", "Naudokite šį nustatymą atsargiai, nes tai gali sugadinti funkcionalumą!")
			add("vjbase.menu.snpc.settings.togglemedics", "Išjungti veikėjų medicininę funkciją")
			add("vjbase.menu.snpc.settings.togglefollowplayer", "Išjungti žaidėjų sekimą")
			add("vjbase.menu.snpc.settings.label3", "Pavyzdžiui: Kai nuspaudžiate klavišą 'E' ant veikėjo, jis jūs seks")
			add("vjbase.menu.snpc.settings.toggleallies", "Išjungti aljansą (Visi tampa priešais)")
			add("vjbase.menu.snpc.settings.togglebecomeenemytoply", "Išjungti saviškių virtimą priešais")
			add("vjbase.menu.snpc.settings.toggleproppush", "Išjungti daiktų stumdymą (Būtybės)")
			add("vjbase.menu.snpc.settings.togglepropattack", "Išjungti daiktų puolimą (Būtybės)")
			add("vjbase.menu.snpc.settings.togglescarednade", "Išjungti paniką nuo granatų")
			add("vjbase.menu.snpc.settings.togglereloading", "Išjungti ginklų užtaisymą")
			add("vjbase.menu.snpc.settings.label4", "Puolimų nustatymai:")
			add("vjbase.menu.snpc.settings.togglemelee", "Išjungti artimąsias atakas")
			add("vjbase.menu.snpc.settings.togglerange", "Išjungti tolimąsias atakas")
			add("vjbase.menu.snpc.settings.toggleleap", "Išjungti šuolio atakas (Būtybės)")
			add("vjbase.menu.snpc.settings.togglethrownade", "Išjungti granatų mėtymą (Žmonės)")
			add("vjbase.menu.snpc.settings.toggleweapons", "Išjungti ginklus (Žmonės)")
			add("vjbase.menu.snpc.settings.label5", "Žmonės nebegalės naudotis ginklais!")
			add("vjbase.menu.snpc.settings.togglemeleedsp", "Išjungti DSP efektą kai artimoji ataka duoda daug žalos")
			add("vjbase.menu.snpc.settings.toggleslowplayer", "Išjungti žaidėjų sulėtėjimą nuo artimųjų atakų")
			add("vjbase.menu.snpc.settings.togglebleedonmelee", "Išjungti žaidėjų/veikėjų kraujavimą nuo artimųjų atakų")
			add("vjbase.menu.snpc.settings.label6", "Įvairūs kiti nustatymai:")
			add("vjbase.menu.snpc.settings.toggleidleparticles", "Išjungti ramybės būsenos efektus")
			add("vjbase.menu.snpc.settings.label7", "Išjungiant tai gali padėti numalšinti lag'ą")
			add("vjbase.menu.snpc.settings.togglesnpcchat", "Išjungti veikėjų chat'ą")
			add("vjbase.menu.snpc.settings.label8", "Pavyzdžiui: 'Scientist is now following you'")
			add("vjbase.menu.snpc.settings.label9", "Žalos bei lavonų nustatymai:")
			add("vjbase.menu.snpc.settings.toggleflinching", "Išjungti krūptelėjimus")
			add("vjbase.menu.snpc.settings.togglebleeding", "Išjungti kraują")
			add("vjbase.menu.snpc.settings.label10", "Išjungia kraujo efektus, kraujo balas ir t.t.")
			add("vjbase.menu.snpc.settings.togglebloodpool", "Išjungti kraujos balas")
			add("vjbase.menu.snpc.settings.togglegib", "Išjungti vidaus organų/dalių išsitaškymus")
			add("vjbase.menu.snpc.settings.label11", "Išjungiant tai gali padėti numalšinti lag'ą")
			add("vjbase.menu.snpc.settings.togglegibdecals", "Išjungti vidaus organų aplinkos teršimą")
			add("vjbase.menu.snpc.settings.togglegibdeathparticles", "Išjungti vidaus organų efektus")
			add("vjbase.menu.snpc.settings.toggledeathanim", "Išjungti mirties animaciją")
			add("vjbase.menu.snpc.settings.togglecorpses", "Išjungti lavonus")
			add("vjbase.menu.snpc.settings.label12", "Pasyvojo mąstymo nustatymai:")
			add("vjbase.menu.snpc.settings.togglerunontouch", "Išjungti panikavimą nuo prisilietimo")
			add("vjbase.menu.snpc.settings.togglerunonhit", "Išjungti panikavimą nuo žalos")
			
			add("vjbase.menu.snpc.sdsettings", "Garso nustatymai")
			add("vjbase.menu.snpc.sdsettings.toggleallsounds", "Išjungti visus garsus")
			add("vjbase.menu.snpc.sdsettings.togglesoundtrack", "Išjungti muziką")
			add("vjbase.menu.snpc.sdsettings.toggleidle", "Išjungti ramybės būsenos garsus")
			add("vjbase.menu.snpc.sdsettings.togglebreathing", "Išjungti kvėpavimo garsus")
			add("vjbase.menu.snpc.sdsettings.togglefootsteps", "Išjungti vaikščiojimo garsus")
			add("vjbase.menu.snpc.sdsettings.toggleattacksounds", "Išjungti artimųjų atakų garsus")
			add("vjbase.menu.snpc.sdsettings.togglemeleemiss", "Išjungti artimosios atakos nepataikymo garsus")
			add("vjbase.menu.snpc.sdsettings.togglerangeattack", "Išjungti tolimųjų atakų garsus")
			add("vjbase.menu.snpc.sdsettings.togglealert", "Išjungti budrumo garsus")
			add("vjbase.menu.snpc.sdsettings.togglepain", "Išjungti skausmo garsus")
			add("vjbase.menu.snpc.sdsettings.toggledeath", "Išjungti mirties garsus")
			add("vjbase.menu.snpc.sdsettings.togglegibbing", "Išjungti išsitaškymo garsus")
			add("vjbase.menu.snpc.sdsettings.label1", "Taip pat galioja ir tiem garsam, kai dalis/organas liečiasi su kažkuo")
			add("vjbase.menu.snpc.sdsettings.togglemedic", "Išjungti medicinos garsus")
			add("vjbase.menu.snpc.sdsettings.togglefollowing", "Išjungti sekimo garsus")
			add("vjbase.menu.snpc.sdsettings.togglecallhelp", "Išjungti pagalbos šaukimo garsus")
			add("vjbase.menu.snpc.sdsettings.togglereceiveorder", "Išjungti gautų įsakymų garsus")
			add("vjbase.menu.snpc.sdsettings.togglebecomeenemy", "Išjungti saviškių virtimą priešais garsus")
			add("vjbase.menu.snpc.sdsettings.toggleplayersight", "Išjungti žaidėjų pamatymo garsus")
			add("vjbase.menu.snpc.sdsettings.label2", "Groja, kai veikėjas (saviškis) pamato žaidėją")
			add("vjbase.menu.snpc.sdsettings.toggledmgbyplayer", "Išjungti žalos nuo žaidėjo garsus")
			add("vjbase.menu.snpc.sdsettings.label3", "Groja, kai žaidėjas sužaloja veikėją, paprastai saviškį.")
			add("vjbase.menu.snpc.sdsettings.toggleleap", "Išjungti šuolio atakos garyss")
			add("vjbase.menu.snpc.sdsettings.toggleslowedplayer", "Išjungti sulėtėjimo garsus")
			add("vjbase.menu.snpc.sdsettings.label4", "Groja, kai žaidėjas yra sulėtinamas artimosios atakos")
			add("vjbase.menu.snpc.sdsettings.togglegrenade", "Išjungti granatų mėtymo garsus")
			add("vjbase.menu.snpc.sdsettings.togglegrenadesight", "Išjungti panikos nuo granatų garsus")
			add("vjbase.menu.snpc.sdsettings.togglesuppressing", "Išjungti nuslopinimo sušukimo garsus")
			add("vjbase.menu.snpc.sdsettings.togglereload", "Išjungti ginklo užtaisymo sušukimo garsus")
			
			add("vjbase.menu.snpc.devsettings", "Programuotojo nustatymai")
			add("vjbase.menu.snpc.devsettings.label1", "Šie nustatymai naudojami kai kūriami nauji „VJ“ veikėjai.")
			add("vjbase.menu.snpc.devsettings.label2", "DĖMESIO: Šie nustatymai gali sukelti lag'ą!")
			add("vjbase.menu.snpc.devsettings.toggledev", "Įjungti programuotojo rėžimą?")
			add("vjbase.menu.snpc.devsettings.label3", "Šis nustatymas turi būti įjungtas iš šio meniu arba per kontekstinį meniu! (Reikalingas nustatymam žemiau)")
			add("vjbase.menu.snpc.devsettings.printtouch", "Spausdinti On Touch (Konsolė)")
			add("vjbase.menu.snpc.devsettings.printcurenemy", "Spausdinti užfiksuotą priešą (Konsolė)")
			add("vjbase.menu.snpc.devsettings.printlastseenenemy", "Spausdinti 'LastSeenEnemy' laiką (Chat'as/konsolė)")
			add("vjbase.menu.snpc.devsettings.printonreset", "Spausdinti On Reset Enemy (Konsolė)")
			add("vjbase.menu.snpc.devsettings.printonstopattack", "Spausdinti On Stopped Attacks (Konsolė)")
			add("vjbase.menu.snpc.devsettings.printtakingcover", "Spausdinti Taking Cover (Konsolė)")
			add("vjbase.menu.snpc.devsettings.printondamage", "Spausdinti On Damage (Konsolė)")
			add("vjbase.menu.snpc.devsettings.printondeath", "Spausdinti On Death (Konsolė)")
			add("vjbase.menu.snpc.devsettings.printweapon", "Spausdinti dabartinį ginklą (Konsolė)")
			add("vjbase.menu.snpc.devsettings.printammo", "Spausdinti amunicijos kiekį (Konsolė)")
			add("vjbase.menu.snpc.devsettings.printaccuracy", "Spausdinti ginklo taiklumą (Konsolė)")
			add("vjbase.menu.snpc.devsettings.cachedmodels", "Talpykloje esantys modeliai (Konsolė)")
			
			add("vjbase.menu.snpc.consettings", "Valdiklio nustatymai")
			add("vjbase.menu.snpc.consettings.label1", "Pastaba: Šie nustatymai veikia tik klieno pusėje!")
			add("vjbase.menu.snpc.consettings.label2", "Ant kiek toli ar arti priartėjimas pasikeičia kiekviena spūstelėjimą")
			add("vjbase.menu.snpc.consettings.displayhud", "Rodyti HUD")
			add("vjbase.menu.snpc.consettings.zoomdistance", "Priartėjimo distancija")
			add("vjbase.menu.snpc.consettings.displaydev", "Rodyti programavimo objektus")
			add("vjbase.menu.snpc.consettings.label3", "Klavišai:")
			add("vjbase.menu.snpc.consettings.bind.header1", "Kontrolė")
			add("vjbase.menu.snpc.consettings.bind.header2", "Aprašymas")
			add("vjbase.menu.snpc.consettings.bind.clickmsg1", "Pasirinktas klavišas:")
			add("vjbase.menu.snpc.consettings.bind.clickmsg2", "Aprašymas:")
			add("vjbase.menu.snpc.consettings.bind.movement", "Judėjimas (Palaiko ir aštuonių krypčių)")
			add("vjbase.menu.snpc.consettings.bind.exitcontrol", "Išeiti iš Valdiklio")
			add("vjbase.menu.snpc.consettings.bind.meleeattack", "Artimoji ataka")
			add("vjbase.menu.snpc.consettings.bind.rangeattack", "Tolimoji / Ginklo ataka")
			add("vjbase.menu.snpc.consettings.bind.leaporgrenade", "Šuolio / Granatos ataka")
			add("vjbase.menu.snpc.consettings.bind.reloadweapon", "Užtaisyti ginklą")
			add("vjbase.menu.snpc.consettings.bind.togglebullseye", "Perjungti taikinio sekimą")
			add("vjbase.menu.snpc.consettings.bind.cameraup", "Pakelti kamerą aukščiau")
			add("vjbase.menu.snpc.consettings.bind.cameradown", "Nuleisti kamerą žemiau")
			add("vjbase.menu.snpc.consettings.bind.cameraforward", "Pastumti kamerą į priekį")
			add("vjbase.menu.snpc.consettings.bind.camerabackward", "Pastumti kamerą atgal")
			add("vjbase.menu.snpc.consettings.bind.cameraleft", "Pastumti kamerą į kairę")
			add("vjbase.menu.snpc.consettings.bind.cameraright", "Pastumti kamerą į dešinę")
			add("vjbase.menu.snpc.consettings.bind.resetzoom", "Atstatyti priartinimą")
			
			-- Weapon Client Settings
			add("vjbase.menu.clweapon", "Kliento nustatymai")
			add("vjbase.menu.clweapon.notice", "Pastaba: šie nustatymai yra klientų, reiškia, jie nesikeis kitiem žmonėm!")
			add("vjbase.menu.clweapon.togglemuzzle", "Išjungti vamzdžio liepsną")
			add("vjbase.menu.clweapon.togglemuzzlelight", "Išjungti vamzdžio liepsnos dinaminę šviesą")
			add("vjbase.menu.clweapon.togglemuzzle.label", "Išjungiant vamzdžio liepsną taip pat išjungs ir susijusius nustatymus")
			add("vjbase.menu.clweapon.togglemuzzlesmoke", "Išjungti vamzdžio liepsnos dūmus")
			add("vjbase.menu.clweapon.togglemuzzleheatwave", "Išjungti vamzdžio liepsnos karščio bangą")
			add("vjbase.menu.clweapon.togglemuzzlebulletshells", "Išjungti apvalkalines kulkas")
			
			-- NPC Properties (C Menu)
			add("vjbase.menuproperties.control", "KONTROLIUOTI")
			add("vjbase.menuproperties.guard", "Perjungti teritorijos saugojimą")
			add("vjbase.menuproperties.wander", "Perjungti klaidžiojimą")
			add("vjbase.menuproperties.medic", "Paversti mediku")
			add("vjbase.menuproperties.allyme", "Paversti saviškiu man")
			add("vjbase.menuproperties.hostileme", "Paversti priešu man")
			add("vjbase.menuproperties.slay", "Nužudyti")
			add("vjbase.menuproperties.gib", "Ištaškyti (jei galima)")
			add("vjbase.menuproperties.devmode", "Įjungti programuotojo rėžimą")
			
			-- Tools
			add("tool.vjstool.menu.tutorialvideo", "Mokomasis vaizdo įrašas (anglų kalba)")
			add("tool.vjstool.menu.label.recommendation", "Rekomenduojama naudoti šį įrankį tik „VJ Base“ veikėjams.")
			
			add("tool.vjstool_bullseye.name", "Veikėjo taikinys")
			add("tool.vjstool_bullseye.desc", "Sukuria taikinį kuri veikėjai puls")
			add("tool.vjstool_bullseye.left", "Sukurti taikinį")
			add("tool.vjstool_bullseye.menu.help1", "Spauskite USE klavišą ant taikinio kad aktyvuotumėte/deaktyvuotumėte.")
			add("tool.vjstool_bullseye.menu.help2", "Kai deaktyvuotas, veikėjai taikinio nepuola.")
			add("tool.vjstool_bullseye.menu.label1", "Pasirinkite judėjimo tipą")
			add("tool.vjstool_bullseye.menu.label2", "Modelių katalogas")
			add("tool.vjstool_bullseye.menu.toggleusestatus", "Naudoti būsenos spalvas (Aktyvuotas/Deaktyvuotas)")
			add("tool.vjstool_bullseye.menu.togglestartactivated", "Iškarto suaktyvintas")
			
			add("tool.vjstool_entityscanner.name", "Objektų skaneris")
			add("tool.vjstool_entityscanner.desc", "Gauna informaciją apie objektą")
			add("tool.vjstool_entityscanner.left", "Išspausdinti informaciją apie objektą konsolėje")
			add("tool.vjstool_entityscanner.label", "Išspausdina informaciją apie bet kokį pasirinktą objektą konsolėje.")
			
			add("tool.vjstool_healthmodifier.name", "Sveikatos modifikatorius")
			add("tool.vjstool_healthmodifier.desc", "Pakeiskite objekto sveikatą")
			add("tool.vjstool_healthmodifier.left", "Nustatykite sveikatą")
			add("tool.vjstool_healthmodifier.right", "Nustatykite sveikatą ir maks. sveikatą")
			add("tool.vjstool_healthmodifier.reload", "Pagydyti objektą iki maksimalaus sveikatos procento")
			add("tool.vjstool_healthmodifier.adminonly", "Tik administratoriai gali keisti sveikatą arba gydyti kitus žaidėjus.")
			add("tool.vjstool_healthmodifier.sliderhealth", "Sveikata")
			add("tool.vjstool_healthmodifier.togglegodmode", "Nemirtingumas")
			add("tool.vjstool_healthmodifier.label", "Šiuo metu veikia tik ant „VJ Base“ veikėjų")
			
			add("tool.vjstool_notarget.name", "Nematomumas")
			add("tool.vjstool_notarget.desc", "Nustatant nematomumą, visi veikėjai negalės „matyti“ tam tikro objekto")
			add("tool.vjstool_notarget.left", "Uždėti nematomumą ant savęs")
			add("tool.vjstool_notarget.right", "Uždėti nematomumą ant veikėjo arba žaidėjo")
			add("tool.vjstool_notarget.label", "Kai nematomumas yra įjungtas and objekto, kiti veikėjai jo nematys.")
			
			add("tool.vjstool_npcequipment.name", "Veikėjų ginklai")
			add("tool.vjstool_npcequipment.desc", "Keičia veikėjų ginklus")
			add("tool.vjstool_npcequipment.left", "Pakeisti veikėjo ginklą")
			add("tool.vjstool_npcequipment.right", "Pašalinti veikėjo ginklą")
			add("tool.vjstool_npcequipment.label", "Pakeičia arba pašalina veikėjo ginklą")
			add("tool.vjstool_npcequipment.selectedequipment", "Pasirinktas ginklas")
			add("tool.vjstool_npcequipment.print.doubleclick", "Spūstelėkite du kartus kad pasirinktumėte ginklą.")
			add("tool.vjstool_npcequipment.print.weaponselected1", "Ginklas")
			add("tool.vjstool_npcequipment.print.weaponselected2", "pasirinktas!")
			add("tool.vjstool_npcequipment.header1", "Pavadinimas")
			add("tool.vjstool_npcequipment.header2", "Klasė")
			
			add("tool.vjstool_npcmover.name", "Veikėjų judinimas")
			add("tool.vjstool_npcmover.desc", "Judina veikėjus, pirmiausia veikėjas turi būti pažymėtas")
			add("tool.vjstool_npcmover.left", "Pažymėkite veikėją")
			add("tool.vjstool_npcmover.right", "Bėgti į nurodytą vietą")
			add("tool.vjstool_npcmover.reload", "Eiti į nurodytą vietą")
			add("tool.vjstool_npcmover.header1", "Pavadinimas")
			add("tool.vjstool_npcmover.header2", "Klasė")
			add("tool.vjstool_npcmover.header3", "Informacija")
			add("tool.vjstool_npcmover.buttonunselectall", "Panaikinti visų veikėjų žymėjimą")
			add("tool.vjstool_npcmover.print.unselectedall", "Atžymėti visi veikėjai!")
			add("tool.vjstool_npcmover.print.unselectedall.error", "Niekas nebuvo atžymėtas")
			
			add("tool.vjstool_npcrelationship.name", "Veikėjų santykių modifikatorius")
			add("tool.vjstool_npcrelationship.desc", "Modifikuoja veikėjų/objektų santykius")
			add("tool.vjstool_npcrelationship.left", "Taikyti santykių lentelę")
			add("tool.vjstool_npcrelationship.right", "Gauti dabartines klases")
			add("tool.vjstool_npcrelationship.reload", "Taikyti santykių lentelę ant savęs")
			add("tool.vjstool_npcrelationship.label1", "Keičia veikėjo santykį su kitais objektais")
			add("tool.vjstool_npcrelationship.header", "Klasifikacija")
			add("tool.vjstool_npcrelationship.label2", "Spūstelėkite „return“ kad pridėti klasifikaciją")
			add("tool.vjstool_npcrelationship.button.combine", "Įdėti „Combine“ imperijos klasifikaciją")
			add("tool.vjstool_npcrelationship.button.antlion", "Įdėti antlionų klasifikaciją")
			add("tool.vjstool_npcrelationship.button.zombie", "Įdėti zombių klasifikaciją")
			add("tool.vjstool_npcrelationship.button.player", "Įdėti žaidėjo klasifikaciją")
			add("tool.vjstool_npcrelationship.togglealliedply", "Draugiškas visiem žaidėjam?")
			add("tool.vjstool_npcrelationship.label3", "Taikomas tik „VJ Base“ veikėjams ir reikia, kad veikėjas turėtų")
			add("tool.vjstool_npcrelationship.print.applied", "Pritaikyta santykių lentelę ant")
			
			add("tool.vjstool_npcspawner.name", "Veikėjų spawner'is")
			add("tool.vjstool_npcspawner.desc", "Sukuria spawner'į")
			add("tool.vjstool_npcspawner.left", "Sukurti spawner'į")
			add("tool.vjstool_npcspawner.right", "Sukurti objektus vieną kartą")
			add("tool.vjstool_npcspawner.selectednpc", "Pasirinktas veikėjas")
			add("tool.vjstool_npcspawner.spawnpos.forward", "Pozicija | Į priekį")
			add("tool.vjstool_npcspawner.spawnpos.right", "Pozicija | Atgal")
			add("tool.vjstool_npcspawner.spawnpos.up", "Pozicija | Į viršų")
			add("tool.vjstool_npcspawner.selectweapon", "Pasirinktas ginklas")
			add("tool.vjstool_npcspawner.button.updatelist", "Atnaujinti sąrašą")
			add("tool.vjstool_npcspawner.label1", "Du kartus spūstelėkite ant punkto, kad jį pašalinti.")
			add("tool.vjstool_npcspawner.header1", "Pavadinimas")
			add("tool.vjstool_npcspawner.header2", "Pozicija")
			add("tool.vjstool_npcspawner.header3", "Ginklas")
			add("tool.vjstool_npcspawner.label2", "Papildomi nustatymai")
			add("tool.vjstool_npcspawner.toggle.spawnsound", "Groti veikėjo sukurimo garsą?")
			add("tool.vjstool_npcspawner.nextspawntime", "Kitas spawn'o laikas")
			add("tool.vjstool_npcspawner.popup.header1", "Pavadinimas")
			add("tool.vjstool_npcspawner.popup.header2", "Klasė")
			add("tool.vjstool_npcspawner.popup.header3", "Kategorija")
			add("tool.vjstool_npcspawner.title1", "Du kartus spūstelėkite, kad pasirinktumėte veikėją.")
			add("tool.vjstool_npcspawner.title2", "Du kartus spūstelėkite, kad pasirinktumėte ginklą.")
		elseif conv == "spanish_lt" then ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		-- General Menu (Used everywhere)
			add("vjbase.menu.general.default", "Predeterminado")
			add("vjbase.menu.general.admin.only", "Nota: Solo admins pueden usar este menú.")
			add("vjbase.menu.general.admin.not", "¡No eres un admin!")
			add("vjbase.menu.general.reset.everything", "Resetear a predeterminado")
			add("vjbase.menu.general.snpc.warnfuture", "ADVERTENCIA: ¡Solamente SNPCs aparecidos en el futuro serán afectados!")
			add("vjbase.menu.general.snpc.creaturesettings", "Opciones de creatura:")
			add("vjbase.menu.general.snpc.humansettings", "Opciones de humano:")
		-- Menu Tabs			
			add("vjbase.menu.tabs.mainmenu", "Menú Principal")
			add("vjbase.menu.tabs.settings.snpc", "Opciones de SNPC")
			add("vjbase.menu.tabs.settings.weapon", "Opciones de Arma")
			add("vjbase.menu.tabs.settings.hud", "Opciones de HUD")
			add("vjbase.menu.tabs.tools", "Herramientas")
			add("vjbase.menu.tabs.configures.snpc", "Configuraciones de SNPC")
		-- Main Menu			
			add("vjbase.menu.cleanup", "Limpiar")
			add("vjbase.menu.cleanup.everything", "Limpiar Todo")
			add("vjbase.menu.cleanup.stopsounds", "Parar Todos los Sonidos")
			add("vjbase.menu.cleanup.remove.vjnpcs", "Remover todos los SNPCs de VJ")
			add("vjbase.menu.cleanup.remove.npcs", "Remover todos los (S)NPCs")
			add("vjbase.menu.cleanup.remove.spawners", "Remover todos los Creadores")
			add("vjbase.menu.cleanup.remove.corpses", "Remover todos los Cadaveres")
			add("vjbase.menu.cleanup.remove.vjgibs", "Remover todos los Gibs VJ")
			add("vjbase.menu.cleanup.remove.groundweapons", "Remover Todas las Armas del suelo")
			add("vjbase.menu.cleanup.remove.props", "Remover todos los Props")
			add("vjbase.menu.cleanup.remove.decals", "Remover todos los Sprays")
			add("vjbase.menu.cleanup.remove.allweapons", "Remover todas tus Armas")
			add("vjbase.menu.cleanup.remove.allammo", "Remover toda tu Munición")
			
			add("vjbase.menu.helpsupport", "Contacto y Apoyo")
			add("vjbase.menu.helpsupport.reportbug", "Reportar un Bug")
			add("vjbase.menu.helpsupport.suggestion", "Sugerir Algo")
			add("vjbase.menu.helpsupport.discord", "¡Unete a mi servidor de Discord!")
			add("vjbase.menu.helpsupport.steam", "¡Unete a mi grupo de Steam!")
			add("vjbase.menu.helpsupport.youtube", "¡Suscribete a mi canal de YouTube!")
			add("vjbase.menu.helpsupport.twitter", "¡Sigueme en Twitter!")
			add("vjbase.menu.helpsupport.patreon", "¡Doname en Patreon!")
			add("vjbase.menu.helpsupport.label1", "¡Sigueme en uno de estos links para estar al pendiente de mis addons!")
			add("vjbase.menu.helpsupport.label2", "¡Las donaciones me ayudan y me motivan a crear/actualizar addons! Gracias!")
			add("vjbase.menu.helpsupport.thanks", "¡Gracias por el apoyo!")
					
			add("vjbase.menu.svsettings", "Ajustes del Servidor Admin")
			add("vjbase.menu.svsettings.label", "ADVERTENCIA: ¡ALGUNOS AJUSTES NECESITAN TENER LOS CHEATS ACTIVADOS!")
			add("vjbase.menu.svsettings.admin.npcproperties", "Restringir Propiedades de SNPCs a solamente Admins")
			add("vjbase.menu.svsettings.noclip", "Permitir NoClip")
			add("vjbase.menu.svsettings.weapons", "Permitir Armas")
			add("vjbase.menu.svsettings.pvp", "Permitir PvP")
			add("vjbase.menu.svsettings.godmode", "Modo Dios (Todos)")
			add("vjbase.menu.svsettings.bonemanip.npcs", "Manipular los huesos de NPCs")
			add("vjbase.menu.svsettings.bonemanip.players", "Manipular los huesos de los Jugadores")
			add("vjbase.menu.svsettings.bonemanip.others", "Manipular los huesos de los Otros")
			add("vjbase.menu.svsettings.timescale.general", "TimeScale General")
			add("vjbase.menu.svsettings.timescale.physics", "TimeScale de Físicas")
			add("vjbase.menu.svsettings.gravity", "Gravedad General")
			add("vjbase.menu.svsettings.maxentsprops", "Máximo de Props/Entidades")
					
			add("vjbase.menu.clsettings", "Ajustes del Cliente")
			add("vjbase.menu.clsettings.label", "Utiliza este menú para personalizar tus ajustes del Cliente, ¡los servidores no pueden cambiar estos ajustes!")
			add("vjbase.menu.clsettings.labellang", "Selección de Idioma")
			add("vjbase.menu.clsettings.notify.lang", "Idioma De VJ Base Establecido Al:")
					
			add("vjbase.menu.info", "Información")
					
			add("vjbase.menu.label", "Plugins Instalados")
			add("vjbase.menu.plugins.label", "Lista de plugins de VJ Base instalados.")
			add("vjbase.menu.plugins.version", "Versión:")
			add("vjbase.menu.plugins.totalplugins", "Total de Plugins:")
			add("vjbase.menu.plugins.header1", "Nombre")
			add("vjbase.menu.plugins.header2", "Tipo")
			add("vjbase.menu.plugins.notfound", "No Se Encontraron Plugins.")
			add("vjbase.menu.plugins.changelog", "Registro de Cambios")
			add("vjbase.menu.plugins.makeaddon", "¿Quieres hacer un addon? ¡Haz Click Aquí! (Link En Inglés)")
					
		elseif conv == "portuguese_br" then ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
			
		end
	
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------ ///// WARNING: Don't touch anything below this line! \\\\\ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	
		print("VJ Base Language Set To: "..conv)
	end
	VJ_REFRESH_LANGUAGE() -- Arachin ankam ganch e, garevor e asiga!
end
