ENT.Base 			= "npc_vj_creature_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Aerial NPC"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Information 	= "Aerial NPC demo for developers.\nBased on the Mortar Synth from Half-Life 2."
ENT.Category		= "VJ Base"